### ISSUE TITLE
Too many layers of symlinks

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6791] opened 2019-08-05 19:40 UTC
# Description

When using the chroot studio with 0.84 development versions, studio commands fail with `/hab/pkgs/core/coreutils/8.30/20190115012313/bin/env: ‘/hab/bin/hab’: Too many levels of symbolic links`.

# Acceptance Criteria
1. `hab pkg build` should not crash a chroot studio due to the binlink in the Studio.

**Comment by dmccown** [comment] 2019-08-05 19:41
https://github.com/habitat-sh/habitat/pull/6700

**Comment by smacfarlane** [comment] 2019-08-05 20:58
I believe the issue is here: https://github.com/habitat-sh/habitat/blob/master/components/hab/src/command/pkg/binlink.rs#L269-L288

We check to verify that the path that we intend to write the script to is not the same as what the `#!` would render as. However, when creating a chroot studio, this is insufficient.  The binlinks are created from outside the studio, before we enter it, so the resulting path will look like `/hab/studios/<normalized_path>/bin/sh`. Since we allow the user to override the `STUDIO_NAME` this is realistically `/some/valid/path/bin/sh` though.   

I can't think of a safe way to test for this when the prefix can be some arbitrary path (not to say one doesn't exist :smile:) , so my gut feeling say we need to provide opt-in/opt-out capabilities for the binlink command.  My preference would be for opt-in as that would preserve existing behavior, while allowing for our users to adopt it as they're ready.  Where this gets tricky though is, from my understanding, that this is required behavior on Windows.  That would leave us with different behaviors on platforms which will inevitably lead to confusion and a bad experience for our users. 

I think in the long run, binstubs are a much safer option for our Linux experience compared to binlinks, but I think it would be best to take an iterative approach to adopting them.

**Comment by baumanj** [comment] 2019-08-05 21:25
> We check to verify that the path that we intend to write the script to is not the same as what the `#!` would render as. However, when creating a chroot studio, this is insufficient. The binlinks are created from outside the studio, before we enter it, so the resulting path will look like `/hab/studios/<normalized_path>/bin/sh`

Could we compare inode numbers (`stat -f "%i" /path/to/file`) to identify whether they refer to the same file?

**Comment by christophermaier** [comment] 2019-08-06 20:34
Is there any way we can programmatically access the full studio prefix to us in comparisons? If not, would that be possible to easily add?

Can we add some tests that exercise this functionality and use that to further characterize the problem?

**Comment by smacfarlane** [comment] 2019-08-06 21:46
> Is there any way we can programmatically access the full studio prefix to us in comparisons? If not, would that be possible to easily add?

@christophermaier I don't think so.  The binlink code doesn't have any context of who/what the caller is, only the destination of where it will write the link.  That does contain the studio root, but `binlink` can't determine which part of it is the studio root.

**Comment by smacfarlane** [comment] 2019-08-07 21:04
Closed by #6796

**Closed by smacfarlane** 2019-08-07 21:04 UTC
Labels: A-studio, C-bug
