### ISSUE TITLE
[builder ui] dropdown menu when avatar is clicked is covered by demo window

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#3876] opened 2017-10-24 00:31 UTC
See the GIF demo:
![dropdown menu hidden by demo window](https://user-images.githubusercontent.com/9401459/31919506-cc10bb36-b817-11e7-9e79-a41c98783c1d.gif)

**Comment by cnunciato** [comment] 2017-10-24 03:39
Duplicate of #3754.

**Closed by cnunciato** 2017-10-24 03:39 UTC
