### ISSUE TITLE
The way to run several similar services based on one package

### ISSUE THREAD

**Issue by guskovd** [habitat-sh/habitat#2474] opened 2017-05-22 20:51 UTC
It would be desirable to understand, whether it is possible services similarly to how it is implemented in systemd templates:

    systemctl start example@1.service
    systemctl start example@2.service

Etc...

**Comment by smith** [comment] 2017-06-02 04:02
Closing as a duplicate of #2520. If I'm misunderstanding, please reopen with more detailed description. Thanks!

**Closed by smith** 2017-06-02 04:02 UTC
