### ISSUE TITLE
[STABILITY] "Service bindings not found - no live members" when live members do exist (42 minute bug)

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#3872] opened 2017-10-23 23:02 UTC
We get into a state where service bindings cannot be found. Eg:
Oct 23 22:57:49 ip-10-0-0-221 hab[13442]: builder-sessionsrv.acceptance(SR): Waiting for service binds...
Oct 23 22:57:50 ip-10-0-0-221 hab[13442]: builder-sessionsrv.acceptance(SR): The specified service group 'builder-datastore.acceptance' for binding 'datastore' is present in the census, but currently has no live members.

This happens every once in a while, even though there is definitely a live member (datastore) in the ring.

**Comment by themightychris** [comment] 2018-06-16 23:15
I'm running into this happening consistently when I `docker-compose up` a second time and containers get reused. If I `docker-compose down` in between then it works.

I found some comments in Slack by @christophermaier  about this issue indicating spec files aren't being cleaned up / updated, which would explain why blowing out the containers fixes the issue. He seemed to indicate the issue would be fixed in 0.56.0 though which is what I'm running

**Comment by christophermaier** [comment] 2018-06-19 18:06
@themightychris Could you link / paste to what I said to refresh my memory? 😆 

Do you have a `docker-compose.yml` file you could share that reliably reproduces this?

**Comment by themightychris** [comment] 2018-06-26 06:00
@christophermaier here you go: https://habitat-sh.slack.com/archives/C0VBY57UP/p1527016765000419
> hrmm... can't' find an issue for it, and it should be gone with 0.56.0 in any event... I think when you `^C` that first service, the spec file isn't getting cleaned up, which means when you start it up again, it's got the old bind information in it.

I can't share mine at the moment but I believe this will happen with ANY docker-compose where one container is passed to another's supervisor as peer. 

But..I've since learned it is just a known thing that you have to run `docker-compose down` after killing `docker-compose up` before you run `docker-compose up` again. The network is in a bad state until you do sooo in that case the error message is correct and it's not habitat's fault :-/

Maybe the original poster was similarly tricked?

**Comment by chefsalim** [comment] 2018-06-26 13:55
@christophermaier the last few times we've built new revs of builder-api, this seems to have triggered consistently in the acceptance env - so it's still around and kicking even with 0.57..

**Comment by christophermaier** [comment] 2018-11-29 23:25
Oops, this got fixed in the [0.64.0](https://github.com/habitat-sh/habitat/tree/0.64.0) release.

**Closed by christophermaier** 2018-11-29 23:25 UTC
Labels: A-supervisor, T-stability, V-sup
