### ISSUE TITLE
`hab studio enter` sets SSL_CERT_FILE environment variable to an invalid value

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#7219] opened 2019-11-20 10:22 UTC
On hab 0.90.6, `hab studio enter` will set the `SSL_CERT_FILE` environment variable inside the studio despite it not being set in the calling user's environment.  The value of the variable may be set to point at a file that does not exist inside the studio, resulting in various failures.

This happens under the following conditions:

1) User does NOT have `SSL_CERT_FILE` already set
2) User is starting a non-docker studio
3) User is starting the studio for the first time, requiring the installation of core/hab-studio
4) The host filesystem contains one of a number preconfigured cert file paths present in the openssl-probe crate.

Here is what I believe is likely happening:

1. In the non-docker branch we install the hab-studio package if it is not already installed:

https://github.com/habitat-sh/habitat/blob/0.90.6/components/hab/src/command/studio/enter.rs#L167
https://github.com/habitat-sh/habitat/blob/0.90.6/components/hab/src/exec.rs#L73

2. In order to make the HTTPS request, this code uses our http client which currently uses the native-tls crate: https://github.com/habitat-sh/habitat/blob/0.90.6/Cargo.lock#L1248-L1262

3. The native-tls crate calls an initialization function which sets `SSL_CERT_FILE` if it is not already set and if one of its pre-defined cert locations is found:

https://github.com/sfackler/rust-native-tls/blob/v0.2.3/src/imp/openssl.rs#L92
https://github.com/alexcrichton/openssl-probe/blob/0.1.2/src/lib.rs#L50

4. The paths found in (3) refer to paths on the studio host which might not be available inside the studio. Further note that (3) will happen _after_ we've attempted to copy the file from the host into the studio, since the library only modifies the environment on creation of the first TLSConnector

https://github.com/habitat-sh/habitat/blob/0.90.6/components/hab/src/command/studio/enter.rs#L121-L126
https://github.com/sfackler/rust-native-tls/blob/v0.2.3/src/imp/openssl.rs#L251

5. Finally, even if that path happened to be mounted into the studio, we munge the SSL_CERT_FILE again to point at the /hab/cache/ssl dir under the assumption that we have copied the file there: 

https://github.com/habitat-sh/habitat/blob/0.90.6/components/studio/bin/hab-studio.sh#L887

**Comment by gavindidrichsen** [comment] 2019-12-04 13:41
core/ansible builds have started to fail in Buildkite even though in local hab studio everything including the tests work fine.

The most recently merged core/ansible PR was in October here https://github.com/habitat-sh/core-plans/pull/3070 (though I don't see a buildkite checklist on this...) while the new open PR https://github.com/habitat-sh/core-plans/pull/3134 fails in Buildkite with:

```bash
Installed /hab/pkgs/ci/ansible/2.9.1/20191128002417/lib/python2.7/site-packages/ansible-2.9.1-py2.7.egg
--
  | Processing dependencies for ansible==2.9.1
  | Searching for cryptography
  | Reading https://pypi.python.org/simple/cryptography/
  | Download error on https://pypi.python.org/simple/cryptography/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726) -- Some packages may not be found!
  | Couldn't find index page for 'cryptography' (maybe misspelled?)
  | Scanning index of all packages (this may take a while)
  | Reading https://pypi.python.org/simple/
  | Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726) -- Some packages may not be found!
  | No local packages or working download links found for cryptography
  | error: Could not find suitable distribution for Requirement.parse('cryptography')
  | ansible: Build time: 1m4s
  | ansible: Exiting on error
  | Script done, file is /src/results/logs/ansible.2019-11-28-002417.log
  | 🚨 Error: The command exited with status 1
```

The only way that I was able to replicate the issue in my local hab studio was:
- **NOT** this``SSL_CERT_FILE='' hab pkg build ...`` 
- **NOT** this ``export SSL_CERT_FILE=''`` within the **do_setup_environment()** in the plan.sh
- but this ``push_buildtime_env SSL_CERT_FILE ''`` which seems to be the only way to push an invalid SSL_CERT_FILE value into the buildtime environment

In a related way, the only thing that fixes buildkite so that it works and sees a valid SSL_CERT_FILE is to add core/cacerts to the plan (proven with this draft PR https://github.com/habitat-sh/core-plans/pull/3149):

```diff
--- a/ansible/plan.sh
+++ b/ansible/plan.sh
@@ -16,6 +16,7 @@ pkg_deps=(
 )
 pkg_build_deps=(
   core/gcc
+  core/cacerts
   core/libyaml
   core/make
 )
@@ -26,6 +27,7 @@ do_setup_environment() {
   push_runtime_env PYTHONPATH "${pkg_prefix}/lib/python2.7/site-packages"
   push_runtime_env ANSIBLE_CONFIG "${pkg_prefix}/etc/ansible.cfg"
   push_buildtime_env LD_LIBRARY_PATH "$(pkg_path_for libffi)/lib"
+  push_buildtime_env SSL_CERT_FILE "$(pkg_path_for cacerts)/ssl/cert.pem"
 }

 do_prepare() {
```

Although the above workaround gets Buildkite to work, it probably should not be added to the core/ansible plan for a number of reasons:
- previous core/ansible PR's merged fine without issue (e.g., https://github.com/habitat-sh/core-plans/pull/3070 in October) and the current PR https://github.com/habitat-sh/core-plans/pull/3134 is just a version uplift.
- all local hab studio building and testing works fine
- Builder itself is not failing to build core/ansible:  I kicked off a test core/ansible build with ``hab bldr job start --group core/ansible...`` and the build job status for the ``1394179300404191232`` group id is successfull.

The likely cause of the problem is within the Buildkite environment itself where it appears to be missing a valid SSL_CERT_FiLE.  This issue is possibly the cause of the Buildkite failure.

**Closed** 2020-01-14 22:42 UTC
Labels: C-bug
