### ISSUE TITLE
[builder-ui] Clicking on origin name should go to origin

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3624] opened 2017-10-08 20:18 UTC
When clicking on the origin name in the page title, I should go the Packages tab for that origin. Currently, I redirect to Search Packages.

![habitat_-_automation_that_travels_with_the_app_](https://user-images.githubusercontent.com/446285/31320546-e5cc6bf2-ac3b-11e7-9525-4a819d5e5592.png)

**Comment by cnunciato** [comment] 2017-12-19 19:29
Closing as duplicate of #3899.

**Closed by cnunciato** 2017-12-19 19:29 UTC
Labels: A-builder, L-javascript
