### ISSUE TITLE
hab setup should allow a user to point to on-prem builder 

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#5074] opened 2018-05-14 16:58 UTC
When setting up on-prem builder, there are a couple of potential customizations that would be nice to have in hab setup:

1. Point to an on-prem builder URL
2. Point to a cert file for the on-prem builder SSL cert

**Comment by ryankeairns** [comment] 2018-06-11 13:41
Duplicate of #4763

**Closed by ryankeairns** 2018-06-11 13:41 UTC
Labels: A-cli, C-feature, L-rust, V-devx
