### ISSUE TITLE
Need a better installation/bootstrap method for hab binary itself and mixlib-install integration

### ISSUE THREAD

**Issue by lamont-granquist** [habitat-sh/habitat#1082] opened 2016-07-19 18:20 UTC
AFAIK right now there's two ways to bootstrap getting hab onto a box:
- The downloads page (which is awful UX for automation)
- Doing a curl | bash of `https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh` which only works on linux and that URL looks hella brittle.

I don't much care about the backend of where the bits come from, but it should probably be made installable from mixlib-install.

**Comment by smith** [comment] 2016-07-19 18:28
It's hosted on Bintray (https://bintray.com/habitat/stable/hab-x86_64-linux/0.8.0-20160708161531#files/linux/x86_64, for example), so whatever we use with Bintray for Chef should work for Habitat too.

**Comment by lamont-granquist** [comment] 2016-07-19 18:31
We currently use omnitruck.  If that's the way forward then we need channels setup in omnitruck so that we can curl bash install.sh there and install it from bintray.  Then the work needs to get done so that mixlib-install could pull it from omnitruck.

Paging @schisamo

**Comment by juliandunn** [comment] 2016-10-07 00:15
I'm not sure this is an issue that is in Habitat's domain to fix. As Nathan mentions, the packages are available from Bintray-format links, which could be automated however you want.

**Comment by lamont-granquist** [comment] 2016-10-07 01:56
Until it gets identified who should fix it and it gets passed off, its still a UX issue encountered while trying to use habitat.

**Comment by jtimberman** [comment] 2016-10-14 17:52
I'm actively working on this and plan to have a PR up soon.

**Comment by reset** [comment] 2016-10-17 18:23
@lamont-granquist the changes in #1364 make this process better, but it doesn't add mixlib-install integration. It's unlikely that somebody from the Habitat team will be adding that in the near future, but we can give you anything you need to get it done!

**Comment by igalic** [comment] 2016-11-26 22:23
is there a way to reproduce whatever is on bintray myself?
I understand that a lot of this centered around docker, but… uhm… `make install` would still be nice.

**Comment by adamhjk** [comment] 2016-11-27 17:58
@igalic that's a slightly different issue. Adding a `make install` development target seems like a fine addition to the `Makefile`. 

I do think we need to provide a less brittle install script, but I wouldn't put it high on the list of things to do this instant.

**Comment by reset** [comment] 2017-03-21 19:29
For the short term, we should document this on the installation page and make these instructions prominent at the top of the README

**Comment by christophermaier** [comment] 2018-03-12 15:52
Closing due to age and the fact that it was likely fixed a long time ago.

**Closed by christophermaier** 2018-03-12 15:52 UTC
Labels: S-needs-discussion
