### ISSUE TITLE
hab pkg install returns 404 Not Found

### ISSUE THREAD

**Issue by alexpop** [habitat-sh/habitat#6433] opened 2019-04-16 17:01 UTC
Hello, with this version of hab:
```
[4][default:/src:0]# hab
hab 0.79.1/20190410220617
```

I'm getting the error below when trying to install a 22MB inspec built package that was provided to me:
```
[10][default:/src:0]# wget https://s3.eu-west-2.amazonaws.com/apop-bucket/chef-inspec-4.0.8-20190415172740-x86_64-linux.hart

[11][default:/src:0]# hab pkg install ./chef-inspec-4.0.8-20190415172740-x86_64-linux.hart
» Installing ./chef-inspec-4.0.8-20190415172740-x86_64-linux.hart
☛ Verifying chef/inspec/4.0.8/20190415172740
↓ Downloading chef-20180516185535 public origin key
✗✗✗
✗✗✗ [404 Not Found]
✗✗✗

[12][default:/src:1]#
```

Would it be possible to provide a more user-friendly error here? Ideally with remediation steps, like using `--force` to install from non-public origins, etc...

**Comment by chefsalim** [comment] 2019-04-16 18:19
This may be a duplicate but it seems to be a good idea to beef up our error messaging for this case

**Comment by baumanj** [comment] 2019-04-16 18:21
Duplicate of https://github.com/habitat-sh/habitat/issues/6333. Please reopen with explanation if this is different and I'm missing it.

**Closed by baumanj** 2019-04-16 18:21 UTC
Labels: C-feature
