### ISSUE TITLE
in certain cases, `hab studio rm` can fail due to stale `LOCK` file

### ISSUE THREAD

**Issue by smartb-pair** [habitat-sh/habitat#4134] opened 2017-11-28 10:44 UTC
We run builds on an Ubuntu VM with Habitat version 0.39.1 currently. We've seen some cases where builds fail with an error like this:
```
root@jenkins-master:/var/lib/jenkins/jobs/<app>/workspace# hab studio rm
   hab-studio: Destroying Studio at /hab/studios/var--lib--jenkins--jobs--<app>--workspace (default)
kill: can't kill pid 11560: No such process
```

We were able to work around this only be doing:
```
rm /hab/studios/var--lib--jenkins--jobs--<app>--workspace/hab/sup/default/LOCK
```

**Comment by rsertelon** [comment] 2017-11-28 13:08
This might be linked to #3865

**Comment by eeyun** [comment] 2017-11-28 18:18
Closing as duplicate of #3865

**Closed by eeyun** 2017-11-28 18:18 UTC
