### ISSUE TITLE
hab config apply: cli docs are auto-generating wrong command

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#3148] opened 2017-09-14 07:07 UTC
If you type `hab config apply --help` this is the output: 

```hab-butterfly-config-apply
Applies a configuration to a group of Habitat Supervisors

USAGE:
    hab-butterfly config apply [OPTIONS] <SERVICE_GROUP> <VERSION_NUMBER> [FILE]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
        --org <ORG>      Name of service organization to use for encryption
    -p, --peer <PEER>    A comma-delimited list of one or more Habitat
                         Supervisor peers (default: 127.0.0.1:9638)
    -r, --ring <RING>    Ring key name, which will encrypt communication
                         messages
    -u, --user <USER>    Name of a user key to use for encryption

ARGS:
    <SERVICE_GROUP>     Target service group (ex: redis.default)
    <VERSION_NUMBER>    A version number (positive integer) for this
                        configuration (ex: 42)
    <FILE>              Path to local file on disk (ex: /tmp/config.toml,
                        default: <stdin>)

```
This should be `hab config apply` not `hab-butterfly config apply`. 

The in-browser tutorial will also need to be updated https://github.com/habitat-sh/habitat/tree/master/www/source/tutorials/get-started/demo/responses

**Comment by tashimi** [comment] 2017-09-14 07:36
Here's another example: 

```
[10][default:/src:0]# hab sup --help
hab-sup 0.31.0/20170907234526

Authors: The Habitat Maintainers <humans@habitat.sh>
The Habitat Supervisor

USAGE:
    hab-sup [FLAGS] <SUBCOMMAND>

FLAGS:
        --no-color    Turn ANSI color off
    -v                Verbose output; shows line numbers
    -h, --help        Prints help information
    -V, --version     Prints version information

SUBCOMMANDS:
    bash      Start an interactive Bash-like shell
    config    Displays the default configuration options for a service
    help      Prints this message or the help of the given subcommand(s)
    load      Load a service to be started and supervised by Habitat from a
              package or artifact. Services started in this manner will
              persist through Supervisor restarts.
    run       Run the Habitat Supervisor
    sh        Start an interactive Bourne-like shell
    start     Start a loaded, but stopped, Habitat service or a transient
              service from a package or artifact. If the Habitat Supervisor
              is not already running this will additionally start one for
              you.
    status    Query the status of Habitat services.
    stop      Stop a running Habitat service.
    term      Gracefully terminate the Habitat Supervisor and all of it's
              running services
    unload    Unload a persistent or transient service started by the
              Habitat supervisor. If the Supervisor is running when the
              service is unloaded the service will be stopped.

[11][default:/src:86]# hab-sup --help
bash: hab-sup: command not found
```

**Comment by tashimi** [comment] 2017-09-14 07:44
The problem with including the dash is pretty consistent. Seeing it for `hab studio` as well.

**Comment by nellshamrell** [comment] 2017-09-26 17:28
See if there is a reasonable way in clap to consistently include a dash?

**Comment by rsertelon** [comment] 2017-12-05 21:59
I don't know if clap allows this. What seems to be done is that `hab` is delegating commands to other binaries (`hab-butterfly` for instance), which should be why this is `hab-butterfly` that is shown in the help message.

@baumanj you've been working on clap related things in habitat recently, do you have any idea if we can improve this?

**Comment by baumanj** [comment] 2017-12-06 15:44
The issue is exactly what @rsertelon said: certain `hab` commands exec other binaries and CLAP just prints the name of the first element of `std::env::args()`.

The plan for fixing https://github.com/habitat-sh/habitat/issues/3130 is to move the CLAP configuration into an independent location (YAML or crate) so that usage information can be printed from whichever command the user invoked.

I'm going to close this since I think it's covered by the other issue.

**Closed by baumanj** 2017-12-06 15:44 UTC
Labels: A-cli, C-bug, E-easy

**Comment by kbknapp** [comment] 2018-02-22 03:29
Going back through old issues on until watch list I noticed this, sorry I didn't notice it earlier!

In the future please feel free to ping me if you have clap related questions. I'm not sure if this issue persists or not, but using [`App::bin_name`](https://docs.rs/clap/2.30.0/clap/struct.App.html#method.bin_name) should solve it. I.e. for `hab-sup` you set `bin_name("hab")` so clap won't use the first value in the attic, but rather whatever value you like. This is used in several cargo subcommands so they don't appear like `cargo cargo-outdated [FLAGS]` but rather `cargo outdated [FLAGS]`
