### ISSUE TITLE
Add Chocolatey instructions for downloading hab on Windows to website

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#3818] opened 2017-10-18 09:53 UTC
As for Homebrew on MacOS, we should also have Chocolatey instructions for installing `hab` on Windows machines on our download page.

But see also #3700 and #3817.

**Comment by mwrock** [comment] 2017-10-18 18:53
Hmm I think this is a duplicate of #3817. The choco instructions were added to the same partial as the brew ones. They just don't show up.

**Closed by mwrock** 2017-10-18 18:53 UTC
Labels: A-habitat.sh, E-easy, L-html-css
