### ISSUE TITLE
Keys as symlinks are not found

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat#2949] opened 2017-08-16 14:47 UTC
I am running hab in a Kubernetes cluster, and in this setting, files passed by the user are symlinks to a `tmpfs` mount.

The problem is that when a key file is a symlink, it doesn't get loaded:

```
/ # ls -al /hab/cache/keys/
total 4
drwxrwxrwt    3 root     root           100 Aug 16 14:17 .
drwxr-xr-x    1 root     root          4096 Jul 26 13:38 ..
drwxr-xr-x    2 root     root            60 Aug 16 14:17 ..8988_16_08_14_17_09.300481026
lrwxrwxrwx    1 root     root            31 Aug 16 14:17 ..data -> ..8988_16_08_14_17_09.300481026
lrwxrwxrwx    1 root     root            37 Aug 16 13:01 ringKey-20170816150641.sym.key -> ..data/ringKey-20170816150641.sym.key

/ # cat /hab/cache/keys/ringKey-20170816150641.sym.key 
SYM-SEC-1
ring-key-20170816102049

rNkJnBqdziUgfvv0xEaijs1lGPfTtpKtX4/LZ2jPqgI=/ 

/ # hab start --ring ringKey core/nginx
hab-sup(ER)[src/error.rs:437:8]: Crypto error: No revisions found for ringKey sym key

```

The reason is probably [here](https://github.com/habitat-sh/habitat/blob/23feac4ad65983de7ccc87b1e2d0291548d2fe92/components/core/src/crypto/keys/mod.rs#L280-L281):  [is_file](https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.is_file) returns `false` for symlinks.

Would it make sense to follow symlinks?

**Comment by christophermaier** [comment] 2017-08-17 14:08
Duplicate of #2939

**Closed by christophermaier** 2017-08-17 14:08 UTC
