### ISSUE TITLE
[builder-web] How to display status/resolution for build failures

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2203] opened 2017-05-01 17:23 UTC
If builder service build(s) fail for any reason, how is that failure status bubbled up to the depot UI? Is there a mechanism to re-try a failed build?

**Comment by tashimi** [comment] 2017-05-01 20:27
Closing as duplicate of #2183 , but this is a good user story for context on what this feature should provide.

**Closed by tashimi** 2017-05-01 20:27 UTC
Labels: Builder, ux
