### ISSUE TITLE
Conditional view with slide toggle

### ISSUE THREAD

**Issue by mgamini** [habitat-sh/habitat#3075] opened 2017-09-01 14:39 UTC
![image](https://user-images.githubusercontent.com/223407/29974681-b7637744-8f01-11e7-9b61-632b856811bd.png)
![image](https://user-images.githubusercontent.com/223407/29974682-b77f2390-8f01-11e7-9cfd-bc4fac90cff2.png)

**Comment by ryankeairns** [comment] 2017-09-01 18:37
@mgamini heads up - you've likely picked up on this - but when you toggle that on it will no longer show the form, but a list of the already provided creds/accounts (which will be added via the Origin > Integrations tab).

![screenshot 2017-09-01 13 36 15](https://user-images.githubusercontent.com/446285/29983257-a1323dfc-8f1a-11e7-94d4-1eb06e8080d7.png)

**Comment by ryankeairns** [comment] 2017-09-01 18:37
this issue may not entail what displays, just wanted to make sure you had the latest :)

**Comment by tashimi** [comment] 2017-09-26 17:41
Closed as duplicate of #3259

**Closed by tashimi** 2017-09-26 17:41 UTC
Labels: A-builder, C-feature, E-easy, L-javascript
