### ISSUE TITLE
`--config-from` appears to be broken

### ISSUE THREAD

**Issue by smartb-pair** [habitat-sh/habitat#3884] opened 2017-10-24 14:43 UTC
Using `0.37.0`, we see behavior where sourcing config from a subdirectory of a habitat project where `--config-from` doesn't appear to result in updated rendered configs:
```
hab svc start <origin>/<app> --config-from ./habitat/dependency_plans/<app>/
```

**Comment by eeyun** [comment] 2017-10-24 17:16
Yep, This is totally something i've seen. I think the last time I ran into this issue it was specific to the use of relative pathing. Either way I think it is most certainly unintended behavior. Could you test your `--config-from` flag with an explicit path and tell me if that gets you around this? I'm marking this as accepted but if we can validate that this is isolated to implicit paths it might make the issue easier to resolve!

**Comment by rsertelon** [comment] 2017-11-27 23:15
@smartb-pair did you have time to confirm @eeyun hunch? :)

**Comment by adamhjk** [comment] 2018-08-16 19:00
I can't reproduce this anymore. If anyone else can, lets re-open it - but it looks fine to me. :)

**Closed by adamhjk** 2018-08-16 19:00 UTC
Labels: A-studio, C-bug, E-easy, L-rust, V-devx
