### ISSUE TITLE
How can configuration files be written to arbitrary locations in the tree?

### ISSUE THREAD

**Issue by StuporHero** [habitat-sh/habitat#1610] opened 2016-12-30 18:25 UTC
It isn't clear to me from the tutorial and the documentation when, how, and where the configuration files are written into the package during a build. In the tutorial, the do_build() and do_install() callbacks are overridden, and there is no logic dealing with the configuration file. There also does not appear to be a default callback dealing with it, and we do not create a hook for it.

My experiments suggest that habitat takes each file within ./habitat/config and its subdirectories, fills in the values, and writes it out to a corresponding subdirectory in ${pkg_prefix}/config. Is that correct? If so, wrapping certain legacy applications will require the ability to place configuration files in arbitrary locations in the tree. If not, we need to update the documentation.

**Comment by mwrock** [comment] 2016-12-30 18:32
There may be a better way but I have dealt with this in an `init` hook:

```
cd "{{pkg.svc_var_path}}/src" || exit
export HOME="{{pkg.svc_var_path}}"
cp -f "{{pkg.svc_config_path}}/appsettings.json" .
```

I just copy the files from the habitat config directory to where the application expects them to be.

**Comment by StuporHero** [comment] 2016-12-31 01:13
Hm. I suppose symlinks would work as well. Eventually, it would be nice to have a declarative way to define where configuration files go, but at this early stage of development, this will suffice. I'll play with this a bit, and then I'll add this to the docs in a PR.

**Comment by mwrock** [comment] 2017-02-07 20:28
This issue is really more of a general usability question and not a bug or code issue. We like to address these kind of issues in either our [discourse forum](https://forums.habitat.sh/) or our [slack channel](http://slack.habitat.sh/). I am going to close this issue but please bring this up in either of the above mentioned venues if you would like to discuss it further.

**Closed by mwrock** 2017-02-07 20:28 UTC
