### ISSUE TITLE
builder service: pushing commit to connected plan doesn't trigger build

### ISSUE THREAD

**Issue by srenatus** [habitat-sh/habitat#4078] opened 2017-11-17 16:23 UTC
- This is the package: https://bldr.habitat.sh/#/pkgs/srenatus/dirserver/builds
- That's the connected repo: https://github.com/srenatus/upspin-habitat

<img width="699" alt="screen shot 2017-11-17 at 17 18 27" src="https://user-images.githubusercontent.com/870638/32957252-713784a8-cbbb-11e7-9395-0fc19f35f69b.png">

- The app is installed and has access to all repos:
<img width="357" alt="screen shot 2017-11-17 at 17 18 56" src="https://user-images.githubusercontent.com/870638/32957253-7155d016-cbbb-11e7-9d88-76f708e184b8.png">

- I've just pushed this commit: https://github.com/srenatus/upspin-habitat/commit/65cd5196a8bb12b0c2c9cdaba7cd69dfda538a87 (straight to master)
- Nothing happened
- Added a `.bldr.toml` with this commit https://github.com/srenatus/upspin-habitat/commit/3870f3da9777bea69288a862000e247d853cf226

- Still nothing happened

Am I missing something? 😃

**Comment by Jrakkez** [comment] 2017-11-17 17:37
Same issue here but ours will build if we update the plan.sh

**Comment by rsertelon** [comment] 2017-11-17 17:58
Have you tried with the `paths` config too? Something like
```
[pkg]
plan_path = "pkg/plan.sh"
paths = [ "pkg/*" ]
```

**Comment by tashimi** [comment] 2017-11-17 18:49
Hi - thanks for reporting this issue. We have reproduced and will be investigating.

**Comment by Jrakkez** [comment] 2017-11-17 18:51
For what it's worth - adding an explicit .bldr.toml did not solve the issue in my case

**Comment by chefsalim** [comment] 2017-12-06 01:47
This issue here is the inclusion of "plan.sh" in the plan_path - the path should NOT include plan.sh. Granted, we should be more forgiving on this, but at the moment, just removing the plan.sh should fix the issue of the build not getting kicked off.  So the .bldr.toml can look like this (in this case, the paths is redundant since it's the same as the plan path).

[pkg]
plan_path = "pkg"

**Comment by chefsalim** [comment] 2017-12-06 01:48
Please re-open if the above does not fix the issue.

**Comment by smartb-pair** [comment] 2017-12-07 14:43
I think we are seeing a related issue with our Plans.  Here's some relevant directory layout and `.bldr.toml` content:

Content of the `habitat` directory at the root our repo (which in turn contains a number of additional Plans under the `plans` dir:
```
habitat
├── composite_plan
│   └── plan.sh
├── config
│   ├── alembic.ini
│   ├── api.env
│   ├── api.ini
│   ├── newrelic_api.ini
│   └── newrelic_background_tasks.ini
├── default.toml
├── hooks
│   ├── health_check
│   ├── init
│   └── run
├── plan.sh
└── plans
    ├── postgresql
    ├── config
    │   ├── functions.sh
    │   ├── pg_hba.conf
    │   ├── pg_ident.conf
    │   ├── postgresql.conf
    │   ├── pwfile
    │   └── recovery.conf
    ├── default.toml
    ├── hooks
    │   ├── health_check
    │   ├── init
    │   ├── reconfigure
    │   ├── run
    │   └── suitability
    └── plan.sh
```
and our `.bldr.toml`:
```
[postgresql]
plan_path = "habitat/plans/postgresql"
paths = [
  "habitat/plans/postgresql/*",
]
```

**Comment by bixu** [comment] 2017-12-15 15:36
* eats 🍿 and waits eagerly *

**Comment by bixu** [comment] 2017-12-15 18:07
Maybe what’s missing here is that, though we have a linked planfile in the root of our repo, pushes to _any file_ in said repo don’t seem to trigger an automated build.

Could it be related to the fact we have planfiles for both public and private packages in the same repo, and both types are linked to their respective Builder origins?

**Comment by chefsalim** [comment] 2017-12-15 22:36
@smartb-pair @bixu what your bldr.toml file is saying is that you want the path that the webhook matches is "habitat/plans/postgresql/*".  So when a file is committed that does not match that path, builder will not issue a build.  

Basically, the rule that has to pass any commit before builder will issue a build is: a plan.sh must exist at the plan_path, and the file path for the committed file must match EITHER the plan_path OR one of the paths specified in the bldr.tom.  Hopefully that helps...

**Comment by smartb-pair** [comment] 2017-12-15 23:08
I’ll look into extending what .bldr.toml covers on Monday and see where we get.

**Comment by tashimi** [comment] 2017-12-16 00:10
Updating docs: https://github.com/habitat-sh/habitat/pull/4318 

Salim's going to file an issue since this is somewhat ambiguous behavior

**Comment by tashimi** [comment] 2017-12-16 00:24
Related: https://github.com/habitat-sh/habitat/issues/4323

**Comment by bixu** [comment] 2017-12-16 11:58
I'm still seeing cases where autobuilds don't fire.  For example, the `smartb/flower` package [here](https://bldr.habitat.sh/#/pkgs/smartb/flower/builds)

Here's the related `.bldr.toml` bit:
```
[flower]
plan_path = "habitat/plans/flower"
```
I made a change to one of the plan's files but haven't seen a build trigger.

**Comment by tashimi** [comment] 2017-12-19 01:38
From @bixu, Here’s an example of a linked plan in Builder that’s not auto-building: https://bldr.habitat.sh/#/pkgs/smartb/api_celeryd_default/settings

**Comment by cnunciato** [comment] 2018-01-19 04:44
FWIW, I hit this on a personal project tonight (a simple one with no `.bldr.toml` and my plan files in a `habitat` directory, same layout as the sample Node app) and was only able to get builds to be triggered if I removed the double-quotes around my `pkg_name` and `pkg_origin` values. (I thought we'd fixed this, but I guess not?)

**Comment by elliott-davis** [comment] 2018-01-25 17:57
Issue moved to [habitat-sh/builder #84](https://github.com/habitat-sh/builder/issues/84) via [**ZenHub**](https://www.zenhub.com/)

**Closed by elliott-davis** 2018-01-25 17:57 UTC
Labels: A-builder, C-emergent
