### ISSUE TITLE
Exporting composite packages to docker

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#3907] opened 2017-10-26 11:46 UTC
Currently attempting this yields the following
```
✗✗✗
✗✗✗ A primary service package could not be determined from: starkandwayne/shield. At least one package with a run hook must be provided.
✗✗✗
```

**Comment by eeyun** [comment] 2017-10-31 17:24
Hmm. Well we definitely SHOULD be able to do this but I'm not certain if this work has been completed yet as composites are basically beta status. @christophermaier when you're around later in the week would you have any clarification on this?

**Comment by eeyun** [comment] 2017-11-07 18:18
So I'm pretty certain this is actually not implemented currently. The good news is it is _definitely_ something we want to do so I'm going to go ahead and flag this with the feature label and dump it into the accepted minor bucket.

**Comment by christophermaier** [comment] 2017-11-07 19:28
@eeyun Right on all counts 👍

**Comment by irvingpop** [comment] 2017-11-17 17:21
@christophermaier @eeyun I have an excellent Patient Zero for y'all 😄

**Comment by schu** [comment] 2017-12-01 10:25
I encounter the same error when using the new kubernetes exporter like

```
sudo \
  HAB_PKG_EXPORT_KUBERNETES_PKG_IDENT=schu/hab-pkg-export-kubernetes \
  HAB_PKG_EXPORT_DOCKER_PKG_IDENT=schu/hab-pkg-export-docker \
  hab pkg export kubernetes \
    --push-image --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD \
    -o demo-service.yaml results/...hart
```

(The `HAB_PKG..._IDENT` vars are due to https://github.com/habitat-sh/habitat/issues/4122)

The package that I try to export isn't a composite package and does have a run hook.

cc @zeenix

**Comment by christophermaier** [comment] 2017-12-04 15:39
@schu That sounds like it might be a potential bug in the Kubernetes exporter, if the hart file in question does indeed have a run hook.

We may need to do some more checks in the Docker exporter itself, though: https://github.com/habitat-sh/habitat/blob/8b672dd39c28deb2060bf93c2ca59d574d8a0390/components/pkg-export-docker/src/build.rs#L375-L385... We may be allowing non-services through.

**Comment by zeenix** [comment] 2017-12-06 12:17
@schu wasn't your issue again (yet unmerged) version of k8s exporter, where I had messed up with rebase? Could you try reproducing against git master?

**Comment by christophermaier** [comment] 2018-11-05 14:56
Yup, closing per https://www.habitat.sh/blog/2018/10/shelving-composites/

**Closed by christophermaier** 2018-11-05 14:56 UTC
Labels: A-plan-build, C-feature, V-devx, V-sup
