### ISSUE TITLE
Supervisor stops running when core/httpd is stopped

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#2153] opened 2017-04-23 16:40 UTC
In a studio , run:

```bash
hab --version
# hab 0.21.0/20170421003135
hab sup run &
hab start core/httpd
hab sup stop core/httpd
# httpd.default(SV): Stopping...
# hab-sup(SV): httpd.default - Shutdown method: Graceful Termination
# hab-sup(SV): httpd.default - process 347 died with exit code 0
# hab-sup(SV): httpd.default - Service exited
# hab-sup(MR): Unable to cleanup service spec for transient service, core/httpd/2.4.23/20170215212244, No such file or directory (os error 2)
# hab-sup(MR): Habitat thanks you - shutting down!
#
# [1]+  Done                    hab sup run
```

Expected behavior: httpd stops, supervisor keeps running

Actual behavior: httpd stops, supervisor stops also

I haven't been able to observe this with any service besides httpd. httpd starts the initial process as root and then a bunch of child processes.

You get the same behavior with the supervisor stopping if you stop httpd by finding its PID and `kill`ing it.

**Comment by reset** [comment] 2017-04-23 20:21
@smith thanks for the report! This is happening because we shutdown the supervisor is the last service to be loaded is unloaded. We don't mean to do this if the supervisor was started with `run` vs `start`.

**Comment by mwrock** [comment] 2017-04-28 19:36
I think the cause may be a bit more nuanced. I had this happen to me a couple times yesterday and it was very random. I did not dig in because I was deep into something else. As a rule, stoping all services in a supervisor seem to keep it running. I'll try httpd to ree if I can get a consistent repro.

**Comment by mwrock** [comment] 2017-04-28 20:47
So I honestly don't know what I was seing yesterday and could just be my own clouded memoty but core/httpd is definitely "special" stopping it kills the supervisor even if other services are running.. Here is my guess as to what is happening, I bet httpd is sending a `SIGINT` to the process group. The supervisor does not startv services in a new group (but it probably should) and it along with all of the other services  are the victims of this signal.

This aligns with a smilar issue I have submitted for windows and we may need to take the same approach for both platforms. If so, I'm going to table this for after chef conf, but want to dig a bit more.

**Comment by mwrock** [comment] 2017-04-29 01:39
So having looked at STRACE logs this is what happens:

1. User runs `hab sup stop core/httpd`
2. supervisor sends SIGTERM to httpd process
3. httpd process sends SIGTERM to its process group
4. supervisor dies

Here is an excerpt od the strace from the running httpd process:

```
17:52:55.103494 --- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=67269, si_uid=0} 
---                                                                                     
17:52:55.103589 rt_sigreturn()          = -1 EINTR (Interrupted system call)            
17:52:55.103695 getpgrp()               = 67268                                         
17:52:55.103759 kill(4294900028, SIGTERM) = 0                                           
```
The first line is the SIGTERM from the supervisor. Next it queries the group. Finally it sends a SIGTERM to the group. That last KILL is confusing. One kills a process group by calling KILL on the negative PID based on the absolute number of the group. So in this case, the group is 67268. httpd sends KILL to -67268. So why 4294900028? 4294900028 would be a result of casting  -67268 to an unsigned int.

**Comment by mwrock** [comment] 2017-04-29 01:43
I think the ultimate remedy will be to launch our processes differently in a separate group. Not only will this protect us from these scenarios where a process is being a good citizen and attempting to cleanup after itself, it will help us to clean up zombies for processes that are not so well behaved.

I'm going to close this and will add a card to be addressed later for this.

**Comment by mwrock** [comment] 2017-05-01 17:34
I'm reopening this because as I thought about this. It's fairly easy to make the change for the supervisor to start processes in their own process group (for linux not windows). I'm going to kepp #2199 but change its scope to be about killing zombies instead of starting processes in new groups.

**Comment by mwrock** [comment] 2017-05-01 17:54
actually I think even killing zombies on linux should be trivial and can be included.

**Closed** 2017-05-02 17:30 UTC
Labels: Bug, Supervisor
