### ISSUE TITLE
Studio doesn't work properly with "vi"

### ISSUE THREAD

**Issue by Priminus** [habitat-sh/habitat#939] opened 2016-06-21 14:41 UTC
I'm running a Virtualbox on Windows with CentOS 7.
When I SSH in from Cygwin and use "vi" from within studio, keystrokes display letters instead (see screenshot).

<img width="830" alt="habitat_editor_issue" src="https://cloud.githubusercontent.com/assets/14960229/16233519/4232d3d2-3801-11e6-92bd-66673b8d70da.png">

I suspected maybe it was Cygwin since Windows isn't supported, but I get similar odd behaviour when running inside of Virtualbox. The difference is keystrokes don't display characters, but "i" doesn't quite enable "Insert Mode" properly (e.g. backspace doesn't backspace).

Possibly no "vi" support?

**Comment by smith** [comment] 2016-06-23 17:59
Pretty sure this doesn't have to do with Habitat but may be related to your terminal settings. Perhaps setting `TERM=xterm` would help or looking at the settings of your terminal emulator.

Closing this, but if you can confirm that this behavior is actually caused by a bug in Habitat, please reopen and we can investigate. Thanks!

**Closed by smith** 2016-06-23 17:59 UTC

**Comment by ElectricWarr** [comment] 2016-07-19 16:30
I have the same issue (albeit on Amazon Linux), and a potential solution:

Seems inside a studio Vim runs in Vi compatability mode - if you type `i` for insert mode, `--INSERT--` isn't displayed and the editor behaves mostly as if you were using Vi.

Entering the command `:set nocp` should make it more usable :+1:
