### ISSUE TITLE
Keys not loaded properly when installing .hart locally

### ISSUE THREAD

**Issue by nathenharvey** [habitat-sh/habitat#1317] opened 2016-10-01 02:40 UTC
Habitat 0.10.2 on Linux.

`hab setup` was run without `sudo`.  Installing a local `.hart` package fails with or without `sudo`.

Workarounds:  

`sudo mkdir -p /hab/cache/keys`

`sudo cp ~/.hab/cache/keys/ORIGIN*.pub /hab/cache/keys/` 

`sudo hab install YOUR.hart`

OR

`HAB_CACHE_KEY_PATH=~/.hab/
cache/keys sudo -E hab install YOUR.hart` (assuming the origin key is in the current user's home directory)

- [x] OS - Ubuntu 14.04
- [x] Debug/backtrace 

installing without sudo:

```
$ RUST_LOG=debug RUST_BACKTRACE=1 hab install nathentest1-mytutorialapp-0.2.0-20161001021247-x86_64-linux.hart
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:hab: clap cli args: ["hab", "install", "nathentest1-mytutorialapp-0.2.0-20161001021247-x86_64-linux.hart"]
DEBUG:hab: remaining cli args: []
DEBUG:habitat_http_client::ssl: Setting CA file for SSL context to: /home/chef/.hab/cache/ssl/cert.pem
DEBUG:habitat_http_client::api_client: User-Agent: hab/0.10.2/20160930230245 (x86_64-linux; 3.13.0-96-generic)
DEBUG:habitat_core::package::archive: content = core/node/4.2.6/20160926154453

DEBUG:habitat_core::package::archive: content = # nathentest1 / mytutorialapp


* __Maintainer__: The Habitat Maintainers <humans@habitat.sh>
* __Version__: 0.2.0
* __Release__: 20161001021247
* __Architecture__: x86_64
* __System__: linux
* __Target__: x86_64-linux
* __Upstream URL__: upstream project's website or home page is not defined
* __License__:
* __Source__: [foo](foo)
* __SHA__: SHA256 checksum not provided or required
* __Path__: `/hab/pkgs/nathentest1/mytutorialapp/0.2.0/20161001021247`
* __Build Dependencies__: no build dependencies or undefined
* __Dependencies__: `core/node `
* __Interpreters__: no interpreters or undefined

\# Plan

\## Build Flags

CFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
CPPFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
CXXFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
LDFLAGS: -L/hab/pkgs/core/node/4.2.6/20160926154453/lib
LD_RUN_PATH: /hab/pkgs/core/node/4.2.6/20160926154453/lib

\## Plan Source

pkg_origin=nathentest1
pkg_name=mytutorialapp
pkg_version=0.2.0
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_license=()
pkg_deps=(core/node)
pkg_expose=(8080)
pkg_source=foo

do_download() {
  return 0
}

do_verify() {
  return 0
}

do_unpack() {
  return 0
}

do_build() {
  # The mytutorialapp source code is in a relative directory, so you must copy the
  # contents of the source directory into your $HAB_CACHE_SRC_PATH/$pkg_dirname as this
  # is the same path that Habitat would use if you downloaded a tarball of the source code.
  cp -vr $PLAN_CONTEXT/../source/* $HAB_CACHE_SRC_PATH/$pkg_dirname

  # This installs both npm as well as the nconf module we listed as a
  # dependency in package.json.
  npm install
}

do_install() {
  # Our source files were copied over to HAB_CACHE_SRC_PATH/$pkg_dirname in do_build(),
  # and now they need to be copied from that directory into the root directory of our package
  # through the use of the pkg_prefix variable.
  cp package.json ${pkg_prefix}
  cp server.js ${pkg_prefix}

  # Copy over the nconf module to the package that we installed in do_build().
  mkdir -p ${pkg_prefix}/node_modules/
  cp -vr node_modules/* ${pkg_prefix}/node_modules/
}

DEBUG:habitat_core::package::archive: content = # Default values that can be updated.

# Message of the Day
message = "Hello, World!"

# The port number that is listening for requests.
port = 8080
DEBUG:habitat_core::package::archive: content = nathentest1/mytutorialapp/0.2.0/20161001021247

DEBUG:habitat_core::package::archive: content = core/gcc-libs/5.2.0/20160612075020
core/glibc/2.22/20160612063629
core/linux-headers/4.3/20160612063537
core/node/4.2.6/20160926154453

DEBUG:habitat_core::package::archive: content = 8080

DEBUG:habitat_common::command::package::install: Found nathentest1/mytutorialapp/0.2.0/20161001021247 in artifact cache, skipping remote download
DEBUG:habitat_core::package::archive: content = core/node/4.2.6/20160926154453

DEBUG:habitat_core::package::archive: content = # nathentest1 / mytutorialapp


* __Maintainer__: The Habitat Maintainers <humans@habitat.sh>
* __Version__: 0.2.0
* __Release__: 20161001021247
* __Architecture__: x86_64
* __System__: linux
* __Target__: x86_64-linux
* __Upstream URL__: upstream project's website or home page is not defined
* __License__:
* __Source__: [foo](foo)
* __SHA__: SHA256 checksum not provided or required
* __Path__: `/hab/pkgs/nathentest1/mytutorialapp/0.2.0/20161001021247`
* __Build Dependencies__: no build dependencies or undefined
* __Dependencies__: `core/node `
* __Interpreters__: no interpreters or undefined

\# Plan

\## Build Flags

CFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
CPPFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
CXXFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
LDFLAGS: -L/hab/pkgs/core/node/4.2.6/20160926154453/lib
LD_RUN_PATH: /hab/pkgs/core/node/4.2.6/20160926154453/lib

\## Plan Source

pkg_origin=nathentest1
pkg_name=mytutorialapp
pkg_version=0.2.0
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_license=()
pkg_deps=(core/node)
pkg_expose=(8080)
pkg_source=foo

do_download() {
  return 0
}

do_verify() {
  return 0
}

do_unpack() {
  return 0
}

do_build() {
  # The mytutorialapp source code is in a relative directory, so you must copy the
  # contents of the source directory into your $HAB_CACHE_SRC_PATH/$pkg_dirname as this
  # is the same path that Habitat would use if you downloaded a tarball of the source code.
  cp -vr $PLAN_CONTEXT/../source/* $HAB_CACHE_SRC_PATH/$pkg_dirname

  # This installs both npm as well as the nconf module we listed as a
  # dependency in package.json.
  npm install
}

do_install() {
  # Our source files were copied over to HAB_CACHE_SRC_PATH/$pkg_dirname in do_build(),
  # and now they need to be copied from that directory into the root directory of our package
  # through the use of the pkg_prefix variable.
  cp package.json ${pkg_prefix}
  cp server.js ${pkg_prefix}

  # Copy over the nconf module to the package that we installed in do_build().
  mkdir -p ${pkg_prefix}/node_modules/
  cp -vr node_modules/* ${pkg_prefix}/node_modules/
}

DEBUG:habitat_core::package::archive: content = # Default values that can be updated.

# Message of the Day
message = "Hello, World!"

# The port number that is listening for requests.
port = 8080
DEBUG:habitat_core::package::archive: content = nathentest1/mytutorialapp/0.2.0/20161001021247

DEBUG:habitat_core::package::archive: content = core/gcc-libs/5.2.0/20160612075020
core/glibc/2.22/20160612063629
core/linux-headers/4.3/20160612063537
core/node/4.2.6/20160926154453

DEBUG:habitat_core::package::archive: content = 8080

DEBUG:habitat_core::crypto::artifact: VERIFIED, checking signed hash against mine
DEBUG:habitat_core::crypto::artifact: Expected hash e6b9464da2eb03a0ecd3f806834c06887513d6b129571477b526ed71c8459c3c
DEBUG:habitat_core::crypto::artifact: My hash e6b9464da2eb03a0ecd3f806834c06887513d6b129571477b526ed71c8459c3c
INFO:habitat_common::command::package::install: Verified nathentest1/mytutorialapp/0.2.0/20161001021247 signed by nathentest1-20161001020954
DEBUG:habitat_core::package::archive: body TDEPS = [core/gcc-libs/5.2.0/20160612075020
core/glibc/2.22/20160612063629
core/linux-headers/4.3/20160612063537
core/node/4.2.6/20160926154453]
DEBUG:habitat_core::package::archive: id TDEPS = [core/gcc-libs/5.2.0/20160612075020]
DEBUG:habitat_core::package::archive: id TDEPS = [core/glibc/2.22/20160612063629]
DEBUG:habitat_core::package::archive: id TDEPS = [core/linux-headers/4.3/20160612063537]
DEBUG:habitat_core::package::archive: id TDEPS = [core/node/4.2.6/20160926154453]
→ Using core/gcc-libs/5.2.0/20160612075020
→ Using core/glibc/2.22/20160612063629
→ Using core/linux-headers/4.3/20160612063537
→ Using core/node/4.2.6/20160926154453
✗✗✗
✗✗✗ Can't create '/hab/pkgs/nathentest1/mytutorialapp/0.2.0/20161001021247' (libarchive err_code=2)
✗✗✗
```

installing *with* sudo:

```
$ RUST_LOG=debug RUST_BACKTRACE=1 sudo -E hab install nathentest1-mytutorialapp-0.2.0-20161001021247-x86_64-linux.hart
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:hab: clap cli args: ["hab", "install", "nathentest1-mytutorialapp-0.2.0-20161001021247-x86_64-linux.hart"]
DEBUG:hab: remaining cli args: []
DEBUG:habitat_http_client::ssl: Setting CA file for SSL context to: /hab/cache/ssl/cert.pem
DEBUG:habitat_http_client::api_client: User-Agent: hab/0.10.2/20160930230245 (x86_64-linux; 3.13.0-96-generic)
DEBUG:habitat_core::package::archive: content = core/node/4.2.6/20160926154453

DEBUG:habitat_core::package::archive: content = # nathentest1 / mytutorialapp


* __Maintainer__: The Habitat Maintainers <humans@habitat.sh>
* __Version__: 0.2.0
* __Release__: 20161001021247
* __Architecture__: x86_64
* __System__: linux
* __Target__: x86_64-linux
* __Upstream URL__: upstream project's website or home page is not defined
* __License__:
* __Source__: [foo](foo)
* __SHA__: SHA256 checksum not provided or required
* __Path__: `/hab/pkgs/nathentest1/mytutorialapp/0.2.0/20161001021247`
* __Build Dependencies__: no build dependencies or undefined
* __Dependencies__: `core/node `
* __Interpreters__: no interpreters or undefined

\# Plan

\## Build Flags

CFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
CPPFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
CXXFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
LDFLAGS: -L/hab/pkgs/core/node/4.2.6/20160926154453/lib
LD_RUN_PATH: /hab/pkgs/core/node/4.2.6/20160926154453/lib

\## Plan Source

pkg_origin=nathentest1
pkg_name=mytutorialapp
pkg_version=0.2.0
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_license=()
pkg_deps=(core/node)
pkg_expose=(8080)
pkg_source=foo

do_download() {
  return 0
}

do_verify() {
  return 0
}

do_unpack() {
  return 0
}

do_build() {
  # The mytutorialapp source code is in a relative directory, so you must copy the
  # contents of the source directory into your $HAB_CACHE_SRC_PATH/$pkg_dirname as this
  # is the same path that Habitat would use if you downloaded a tarball of the source code.
  cp -vr $PLAN_CONTEXT/../source/* $HAB_CACHE_SRC_PATH/$pkg_dirname

  # This installs both npm as well as the nconf module we listed as a
  # dependency in package.json.
  npm install
}

do_install() {
  # Our source files were copied over to HAB_CACHE_SRC_PATH/$pkg_dirname in do_build(),
  # and now they need to be copied from that directory into the root directory of our package
  # through the use of the pkg_prefix variable.
  cp package.json ${pkg_prefix}
  cp server.js ${pkg_prefix}

  # Copy over the nconf module to the package that we installed in do_build().
  mkdir -p ${pkg_prefix}/node_modules/
  cp -vr node_modules/* ${pkg_prefix}/node_modules/
}

DEBUG:habitat_core::package::archive: content = # Default values that can be updated.

\# Message of the Day
message = "Hello, World!"

\# The port number that is listening for requests.
port = 8080
DEBUG:habitat_core::package::archive: content = nathentest1/mytutorialapp/0.2.0/20161001021247

DEBUG:habitat_core::package::archive: content = core/gcc-libs/5.2.0/20160612075020
core/glibc/2.22/20160612063629
core/linux-headers/4.3/20160612063537
core/node/4.2.6/20160926154453

DEBUG:habitat_core::package::archive: content = 8080

DEBUG:habitat_common::command::package::install: Found nathentest1/mytutorialapp/0.2.0/20161001021247 in artifact cache, skipping remote download
DEBUG:habitat_core::package::archive: content = core/node/4.2.6/20160926154453

DEBUG:habitat_core::package::archive: content = # nathentest1 / mytutorialapp


* __Maintainer__: The Habitat Maintainers <humans@habitat.sh>
* __Version__: 0.2.0
* __Release__: 20161001021247
* __Architecture__: x86_64
* __System__: linux
* __Target__: x86_64-linux
* __Upstream URL__: upstream project's website or home page is not defined
* __License__:
* __Source__: [foo](foo)
* __SHA__: SHA256 checksum not provided or required
* __Path__: `/hab/pkgs/nathentest1/mytutorialapp/0.2.0/20161001021247`
* __Build Dependencies__: no build dependencies or undefined
* __Dependencies__: `core/node `
* __Interpreters__: no interpreters or undefined

\# Plan

\## Build Flags

CFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
CPPFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
CXXFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
LDFLAGS: -L/hab/pkgs/core/node/4.2.6/20160926154453/lib
LD_RUN_PATH: /hab/pkgs/core/node/4.2.6/20160926154453/lib

\## Plan Source

pkg_origin=nathentest1
pkg_name=mytutorialapp
pkg_version=0.2.0
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_license=()
pkg_deps=(core/node)
pkg_expose=(8080)
pkg_source=foo

do_download() {
  return 0
}

do_verify() {
  return 0
}

do_unpack() {
  return 0
}

do_build() {
  # The mytutorialapp source code is in a relative directory, so you must copy the
  # contents of the source directory into your $HAB_CACHE_SRC_PATH/$pkg_dirname as this
  # is the same path that Habitat would use if you downloaded a tarball of the source code.
  cp -vr $PLAN_CONTEXT/../source/* $HAB_CACHE_SRC_PATH/$pkg_dirname

  # This installs both npm as well as the nconf module we listed as a
  # dependency in package.json.
  npm install
}

do_install() {
  # Our source files were copied over to HAB_CACHE_SRC_PATH/$pkg_dirname in do_build(),
  # and now they need to be copied from that directory into the root directory of our package
  # through the use of the pkg_prefix variable.
  cp package.json ${pkg_prefix}
  cp server.js ${pkg_prefix}

  # Copy over the nconf module to the package that we installed in do_build().
  mkdir -p ${pkg_prefix}/node_modules/
  cp -vr node_modules/* ${pkg_prefix}/node_modules/
}

DEBUG:habitat_core::package::archive: content = # Default values that can be updated.

\# Message of the Day
message = "Hello, World!"

\# The port number that is listening for requests.
port = 8080
DEBUG:habitat_core::package::archive: content = nathentest1/mytutorialapp/0.2.0/20161001021247

DEBUG:habitat_core::package::archive: content = core/gcc-libs/5.2.0/20160612075020
core/glibc/2.22/20160612063629
core/linux-headers/4.3/20160612063537
core/node/4.2.6/20160926154453

DEBUG:habitat_core::package::archive: content = 8080

↓ Downloading nathentest1-20161001020954 public origin key
DEBUG:habitat_http_client::api_client: GET https://willem.habitat.sh/v1/depot/origins/nathentest1/keys/20161001020954 with ApiClient { endpoint: "https://willem.habitat.sh/v1/depot", inner: Client { redirect_policy: FollowAll, read_timeout: None, write_timeout: None, proxy: None }, proxy: None, target_scheme: "https", user_agent_header: UserAgent("hab/0.10.2/20160930230245 (x86_64-linux; 3.13.0-96-generic)") }
DEBUG:hyper::net: http scheme
DEBUG:hyper::net: https scheme
DEBUG:hyper::http::h1: request line: Get "/v1/depot/origins/nathentest1/keys/20161001020954" Http11
DEBUG:hyper::http::h1: headers=Headers { Host: willem.habitat.sh, User-Agent: hab/0.10.2/20160930230245 (x86_64-linux; 3.13.0-96-generic), }
DEBUG:hyper::client::response: version=Http11, status=NotFound
DEBUG:hyper::client::response: headers=Headers { Connection: keep-alive, Fastly-Debug-Digest: cf2a099206e44e1e99e65b06cc92dbdedb8ed48ccf12d89286ecedd4edb71c16, Access-Control-Allow-Origin: *, Server: nginx/1.10.1, Via: 1.1 varnish1.1 varnish, Accept-Ranges: bytes, Strict-Transport-Security: max-age= 7776000; includeSubDomains, X-Cache: MISS, MISS, Access-Control-Allow-Methods: PUT, DELETE, X-Cache-Hits: 0, 0, X-Served-By: cache-sea1924-SEA, cache-jfk8150-JFK, X-Frame-Options: SAMEORIGIN, Date: Sat, 01 Oct 2016 02:32:47 GMT, Access-Control-Allow-Headers: authorization, range, Content-Length: 0, Age: 0, }
DEBUG:habitat_depot_client: Response: Response { status: NotFound, headers: Headers { Connection: keep-alive, Fastly-Debug-Digest: cf2a099206e44e1e99e65b06cc92dbdedb8ed48ccf12d89286ecedd4edb71c16, Access-Control-Allow-Origin: *, Server: nginx/1.10.1, Via: 1.1 varnish1.1 varnish, Accept-Ranges: bytes, Strict-Transport-Security: max-age= 7776000; includeSubDomains, X-Cache: MISS, MISS, Access-Control-Allow-Methods: PUT, DELETE, X-Cache-Hits: 0, 0, X-Served-By: cache-sea1924-SEA, cache-jfk8150-JFK, X-Frame-Options: SAMEORIGIN, Date: Sat, 01 Oct 2016 02:32:47 GMT, Access-Control-Allow-Headers: authorization, range, Content-Length: 0, Age: 0, }, version: Http11, url: "https://willem.habitat.sh/v1/depot/origins/nathentest1/keys/20161001020954", status_raw: RawStatus(404, "Not Found"), message: Http11Message { is_proxied: false, method: None, stream: Wrapper { obj: Some(Reading(SizedReader(remaining=0))) } } }
✗✗✗
✗✗✗ [404 Not Found]
✗✗✗
```

- [x] Current Habitat environment variables where the `hab` command or supervisor is running.  NONE
- [x] If this is a key related issue, please include the list of files (including user/group permissions) in `/hab/cache/keys` and `$HOME/.hab/cache/keys` via `ls -la`.

		ls -la /hab/cache/keys
                ls: cannot access /hab/cache/keys: No such file or directory

		ls -la $HOME/.hab/cache/keys
                total 24
                drwxrwxr-x 2 chef chef 4096 Oct  1 02:18 .
                drwxrwxr-x 6 chef chef 4096 Oct  1 02:18 ..
                -rw-rw-r-- 1 chef chef   75 Oct  1 02:18 core-20160612031944.pub
                -rw-r--r-- 1 root root   75 Oct  1 02:12 core-20160810182414.pub
                -r-------- 1 chef chef   82 Oct  1 02:09 nathentest1-20161001020954.pub
                -r-------- 1 chef chef  126 Oct  1 02:09 nathentest1-20161001020954.sig.key

**Comment by smurawski** [comment] 2016-10-01 04:32
@fnichol - I think this also needs some of your sudo awareness love.  I think we should be able to use https://github.com/habitat-sh/habitat/blob/master/components/core/src/env.rs#L130 in evaluating where to read keys from https://github.com/habitat-sh/habitat/blob/master/components/core/src/fs.rs#L117.

**Comment by juliandunn** [comment] 2016-10-01 04:37
I hesitate to classify this is a "bug" per se. I think it is working as defined, i.e. if you install a local package, the public keys have to come from somewhere. I'm not sure that blindly copying them from a user's `~/.hab/cache/keys` is the right answer.

**Comment by smurawski** [comment] 2016-10-01 04:40
To me it's the same expected behavior as with build (at least in my view), where if I'm running via sudo I'd expect it to pull my user keys not root's.

**Comment by juliandunn** [comment] 2016-10-01 04:48
Yeah... I'm suggesting this has nothing to do with `sudo` versus non-`sudo`.

The generic user job is that I have an arbitrary local `.hart` and I want to install it and run it. Maybe I didn't even just build that `.hart`; my-coworker handed it to me on a USB stick or something. The behavior is currently undefined as to what Habitat should do if it doesn't have the public origin key for a local `.hart`. Try to get it from a depot? Try to copy it from a user's home directory?

I think my opening position would be that it should fail and do nothing and let the user know they need to install the public origin key in some way.

**Comment by reset** [comment] 2016-10-01 19:54
@jdunn what do you think about this flow:

1. Attempt to copy from local sources we have access to
1. Attempt to download from remote
1. If all else fails ask the user to install manually

**Comment by juliandunn** [comment] 2016-10-01 21:18
@reset that seems reasonable. I might even reverse #2 and #1. (#2 is what `yum` will try to do if you `localinstall`)

**Comment by reset** [comment] 2016-10-01 23:41
@juliandunn I think a good way to judge the precedence between 1 & 2 would be to weigh if we want the system config to take precedence over the user level configuration or the other way around

**Comment by nathenharvey** [comment] 2016-10-02 01:50
At least I have a better work around now.  

Just need to copy over the `.pub` half of the key or can use `HAB_CACHE_KEY_PATH=~/.hab/cache/keys sudo -E hab install ...`

Thanks!

**Comment by fnichol** [comment] 2016-10-04 20:32
Yep, this is essentially working as designed (currently). There is **no** special sudo logic around install, only around the `hab studio *` and `hab pkg build *` invocations. When installing a package, you need root permissions to extract under `/hab/pkgs`, set uids/gids, etc.

There are 2 install cases 1) remote from Depot and 2) local from `.hart`. It looks like we're dealing with the second case here.

In all install cases, public origin keys are checked for under `/hab/cache/keys` and need to be present there in order for the package verification to succeed. If we cannot find the public origin key (with revision) that signed the package, the code then goes to the Depot to download the specific key.

At a minimum we should fail with a useful error message to the effect of "To verify this package we could not find the public origin key <name>-<rev> locally under `/hab/cache/keys` nor in the Depot."

@nathenharvey If you need to install that public key you could run a `hab origin key export nathentest1 | sudo hab origin key import` (note the second import uses sudo because we want it installed into the root key cache). Alternatively, you could upload the key with `hab origin key upload nathentest1`.

A tweak we could make to the local `.hart` install logic is to look in the same directory as the `.hart` file for any missing public origin keys which is something we don't currently do. The expectation was that your public origin key is already shared for others on the Depot. Does this make sense?

**Comment by nathenharvey** [comment] 2016-10-05 03:08
This all makes good sense to me.  At this point, I'm OK with closing this out and calling it a failed understanding on my part.

**Comment by juliandunn** [comment] 2016-10-05 04:20
Thanks for the feedback @nathenharvey though I think there is at least a UX improvement we could make here. The minimum we should do is to output an proper error message when a package can't be installed because of a missing public origin key, and give the user a suggestion. This seems like the least amount of work. Example:

**Current behavior**

```
"Can't create '/hab/pkgs/nathentest1/mytutorialapp/0.2.0/20161001021247' (libarchive err_code=2)
✗✗✗"
```

**Suggested behavior**

```
Failed to install package: signing key for `nathentest1/mytutorialapp` not found. Do you need to install it with "hab origin key download nathentest1" as root?
```

**Comment by reset** [comment] 2016-10-05 06:50
@juliandunn @fnichol one approach to making this better could be just switching on the err_code from libarchive and printing what it means along with what we were doing when it happened. Huge improvements to be had reporting failures back on extraction!

**Comment by fnichol** [comment] 2016-10-05 16:17
@reset The change in #1325 already address the libarchive failure--we stop the user from proceeding to install if they are not root so we've dealt with the first half of Nathen's report (thank you @nathenharvey for the supporting UX failure case).

@juliandunn Your suggested behavior is where I was going with my reasoning above to handle the second half of the report.

**Comment by scarolan** [comment] 2016-10-08 19:10
Forgive my ignorance.  Why are keys required for a local installation of a hart artifact?

**Comment by smurawski** [comment] 2016-10-08 19:56
@scarolan the public key for the package signer has to be in `/hab/cache/keys`.

**Comment by nathenharvey** [comment] 2016-10-08 22:01
@scarolan as to they "why"...the supervisor must check the validity of the package (safe by default) before installing it.  It must have the origin key to do so.

**Comment by juliandunn** [comment] 2016-10-09 23:30
I'm going to close this issue for now. #1325 improves the user experience to prevent people from installing when they aren't root. I will likely follow up with some documentation / post on the Habitat forum that provides a clearer explanation of the types of keys utilized by Habitat and where.

**Closed by juliandunn** 2016-10-09 23:30 UTC
Labels: Discussing
