### ISSUE TITLE
Reconfigure hook not triggering when service group topology changes

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#1984] opened 2017-03-23 18:55 UTC
As reported by @moretea, the `reconfigure` hook is not being triggered when the topology of a service that you're observing changes.

**Comment by bodymindarts** [comment] 2017-03-23 19:08
`reconfigure` gets triggered when any file under `{{pkg.svc_config_path}}` changes. If a file exits that depends on `{{svc.me.leader}}` or `{{svc.me.follower}}` then `reconfiguration` will get called.

**Comment by mwrock** [comment] 2017-03-23 20:25
I'm able to repro locally. I don't see a reconfigure firing as I add/remove services to a group.

It looks like we only reconfigure when one of the config templates has changed: https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/service/mod.rs#L397

I think we need to move `self.needs_reconfiguration = true`  outside of that `match` and push it justy under `if svc_cfg_updated || census_updated`.

I'll submit a PR with that

**Comment by mwrock** [comment] 2017-03-23 20:38
that actually might not be the right thing to do. looking at a few more things...

**Comment by mwrock** [comment] 2017-03-23 20:41
yeah definitely not the right thing. I think the code "as is" is correct. I dont see a reconfigure in my environment because my configuration is not topology dependent. But I'll run through that locally just for sanity.

**Comment by mwrock** [comment] 2017-03-23 20:52
I can confirm reconfigure is firing for me with config templates that depend on topology info. @moretea, can you verify that your config templates are referencing service configuration impacted by other services? If so, could you share/link to those configs?

**Comment by moretea** [comment] 2017-03-24 08:36
Ah, I did not have _any_ configuration template defined.

**Comment by mwrock** [comment] 2017-03-25 01:24
Ahh. ok. I'm going to close this issue. Currently the intent of the reconfigure hook is to fire on changes to service configuration. I can definitely see how a hook for any change in topology could be usefull. Please oprn a new issue if you would like to pursue that discussion.

**Closed by mwrock** 2017-03-25 01:24 UTC
