### ISSUE TITLE
[builder-web] Update the Explore view with select static data

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#2367] opened 2017-05-15 17:06 UTC
While we develop APIs for the **Popular Packages**, **Top Dependencies** and **Recently Added** sections of the view, let's fill out these sections with some options that make sense.

**Comment by ryankeairns** [comment] 2017-05-17 12:35
Closing this as a duplicate of #2181 
Static content has been added there and there and merged in PR #2387

**Closed by ryankeairns** 2017-05-17 12:35 UTC
Labels: Papercut
