### ISSUE TITLE
[Documentation] Expand the current studio page

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2585] opened 2017-06-13 20:07 UTC
Ideas from some community members: 

1) `hab studio run nano` is the equivalent of:
 
[host]$ hab studio enter
[studio]$ nano
[studio]$ exit

2) You could do a `hab studio run "hab pkg export docker <package>"` on OSX/Windows, rather than entering the studio and then running the export since you can't natively run hab pkg export docker on non Linux OS

**Comment by eeyun** [comment] 2017-06-20 19:27
This points to a bigger problem I think but it could solve for both cases: Habitat was built explicitly with CI/CD in mind and so our tutorials and documentation should do a good job of explaining the above concept. I think this is an easy question that comes up frequently so we should add some documentation on this use case.

The location of that documentation is up for debate. To an extent I think it might be best served living in the upcoming rewrite of the habitat README.md

**Comment by eeyun** [comment] 2017-06-20 20:48
Closing https://github.com/habitat-sh/habitat/issues/2581 in favor of this issue. Both of these are inherently linked. If we expand the studio concepts page it wouldn't be a bad idea to link to the readme or to have the information on running commands from outside the studio living in both places.

**Comment by ShalokShalom** [comment] 2017-06-22 18:59
Currently, there is no result of: https://www.habitat.sh/docs/search/?q=delete+studio

(I would have preferred to close this issue in favor of the other one, since that one here is more specific.)

**Comment by ShalokShalom** [comment] 2017-06-23 09:13
This is again something, why i like to keep the old issue: 

1) Explain where the studios are: /hab/studios/

2) Explain, how an issues looks like, when one studio is messed up (so one can solve this by creating a new one)

3) Plus all that parts of course: https://github.com/habitat-sh/habitat/issues/2581#issue-235671518

**Comment by reset** [comment] 2017-08-10 19:51
Duplicate of #2882

**Closed by reset** 2017-08-10 19:51 UTC
Labels: A-documentation, C-chore, E-less-easy

**Comment by ShalokShalom** [comment] 2017-08-10 20:50
@reset I see different content, while the topic is the same.
