### ISSUE TITLE
Config updates not propagated via bindings

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2134] opened 2017-04-20 09:22 UTC
While hacking on https://github.com/habitat-sh/habitat/issues/2002 I noticed that changes applied to a configuration that affect an exposed property are not being propagated.

The consuming service will always contain the property that was originally set.

**Comment by reset** [comment] 2017-04-20 19:26
Duplicate of #1816, gonna close this one and track there!

**Closed by reset** 2017-04-20 19:26 UTC
Labels: Bug
