### ISSUE TITLE
Builder UI should show multi-architecture packages correctly

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#5649] opened 2018-09-18 17:57 UTC

**Comment by chefsalim** [comment] 2018-09-18 18:01
Currently, if a Linux2 package is uploaded, the Builder UI is missing the following:
1. Shows "No available artifacts" in the "Latest" tab
2. Shows blank on the "Supported platforms" section in the "Latest" tab
3. Shows "None" in the "Latest stable" section in the "Latest" tab
4. Shows blank "Supported platforms" in the "Versions" tab

For an example, see https://bldr.acceptance.habitat.sh/#/pkgs/smacfarlane/empty-package/latest

**Comment by apriofrost** [comment] 2019-08-05 19:37
Duplicate of #1098

**Closed by apriofrost** 2019-08-05 19:37 UTC
Labels: A-builder, C-feature, V-bldr, V-front-end
