### ISSUE TITLE
[Documentation] Expand the current studio page

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2581] opened 2017-06-13 19:46 UTC
Expand the current studio page: https://www.habitat.sh/docs/concepts-studio/

0) I think it's senseful to explain the fact, that different studios get created when entered in different places, plus its own pros and cons.

1)  I think it's more useful to create one directory where all plans take place and I create one studio there. Under the line, this is the most KISS solution I can think about. See also this issue here in relation:  https://github.com/habitat-sh/habitat/issues/2556

2) Explain that the studio is a chroot on Linux and a Docker container in OSX/Windows, plus what this means for the users

3) Explain how to kill a chroot/Docker studio and why

4) Document baseimage, busybox and stage1, the studio types

**Comment by eeyun** [comment] 2017-06-20 20:50
This issue is very similar in scope to #2585 closing this issue in support of that. Lets bundle the studio documentation issue into a single scoped piece of work.

**Closed by eeyun** 2017-06-20 20:50 UTC
Labels: A-documentation, C-chore, E-easy

**Comment by reset** [comment] 2017-08-10 19:51
Duplicate of #2882
