### ISSUE TITLE
Builds do not start automatically when `habitat/plan.sh` is not in the root of the repository

### ISSUE THREAD

**Issue by nathenharvey** [habitat-sh/habitat#4148] opened 2017-11-29 03:38 UTC
* Package:  nathenharvey/gs-rest-service
* GitHub:  https://github.com/nathenharvey/gs-rest-service/
* Plan file - https://github.com/nathenharvey/gs-rest-service/blob/master/complete/habitat/plan.sh

The plan.sh is in `complete/habitat`, a subdirectory of that repository.  When changes are made and pushed to master, no build is initiated.

The project only builds when clicking the "Build latest version" button on https://bldr.habitat.sh/#/pkgs/nathenharvey/gs-rest-service/latest.

**Comment by rsertelon** [comment] 2017-11-29 08:35
Hey @nathenharvey I think there's an open issue on the subject here: #4078 

Can you try adding a `.bldr.toml` file in your repository (at the root) with something like https://github.com/habitat-sh/habitat/issues/4078#issuecomment-345316894 ?

If it does work, then you've encountered the same problem I think. Thanks for your help :)

**Comment by nathenharvey** [comment] 2017-11-29 16:13
@rsertelon thanks for the help!  I do not think that fixed the issue for me...

the `bldr.toml` was added in https://github.com/nathenharvey/gs-rest-service/commit/6257b7cf082670a02fba3a0694f45f5c3c5b093f

This commit was pushed to master - https://github.com/nathenharvey/gs-rest-service/commit/701be873f23b5b1b6ff87fee281389de43cbc0c7

The build did not automatically kick-off

**Comment by eeyun** [comment] 2018-01-30 18:52
This is definitely an issue we're aware of #4078 actually  has been closed as we migrated that issue over to habitat-sh/build and it is now issue number #84. 

We think this issue might actually be the same as the other issue which is that if you have a .bldr.toml file in place in the repo and you push a change to the source code you don't get a build.

The only way that I've seen getting the builds to kick off automatically are by modifying the planfile itself which we thing is the actual bug here. I'm going to close this as a duplicate of habitat-sh/builder/#84. If there is reason to believe this behavior isn't bound up in that issue please feel free to reopen it!

**Closed by eeyun** 2018-01-30 18:52 UTC
