### ISSUE TITLE
Supervisor randomly exits

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#5312] opened 2018-07-11 20:38 UTC
We see this in the builder dev environment quite often - the supervisor will exit randomly.  

For example:
```
1   [5][default:/src:0]# bb originsrv
  1 ✗✗✗
  2 ✗✗✗ Connection refused (os error 111)
  3 ✗✗✗
  4 ✗✗✗
  5 ✗✗✗ Connection refused (os error 111)
  6 ✗✗✗
  7 [1]+  Done                    hab sup run "$@" > /hab/sup/default/sup.log 2>    &1  (wd: /)
  8 (wd now: /src)
  9 ERROR: _build-builder originsrv aborted due to error
```

This one was after a clean studio enter on the builder repo, which stated services without any (apparent) issues.

**Comment by chefsalim** [comment] 2018-07-11 20:51
Sup log snippet:
```
...

[32mbuilder-api.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:29Z: hyper::server: Incoming stream
[32mbuilder-api.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:29Z: hyper::server::request: Request Line: Head AbsolutePath("/v1/status") Http10
[32mbuilder-api.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:29Z: hyper::server::request: Headers { Host: backend
[32mbuilder-api.default[0m([1;37mO[0m): , Connection: close
[32mbuilder-api.default[0m([1;37mO[0m): , User-Agent: curl/7.54.1
[32mbuilder-api.default[0m([1;37mO[0m): , Accept: */*
[32mbuilder-api.default[0m([1;37mO[0m): , }
[32mbuilder-api.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:29Z: hyper::server::response: writing head: Http10 Ok
[32mbuilder-api.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:29Z: hyper::server::response: headers [
[32mbuilder-api.default[0m([1;37mO[0m): Headers { Access-Control-Allow-Origin: *
[32mbuilder-api.default[0m([1;37mO[0m): , Access-Control-Allow-Headers: authorization, range
[32mbuilder-api.default[0m([1;37mO[0m): , Access-Control-Allow-Methods: PUT, DELETE, PATCH
[32mbuilder-api.default[0m([1;37mO[0m): , Access-Control-Expose-Headers: content-disposition
[32mbuilder-api.default[0m([1;37mO[0m): , Content-Length: 0
[32mbuilder-api.default[0m([1;37mO[0m): , Date: Wed, 11 Jul 2018 20:23:29 GMT
[32mbuilder-api.default[0m([1;37mO[0m): , }]
[32mbuilder-api.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:29Z: zmq: socket dropped
[32mbuilder-api.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:29Z: hyper::server: keep_alive = false for 127.0.0.1:53732
[32mbuilder-api.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:29Z: hyper::server: keep_alive loop ending for 127.0.0.1:53732
[36mhab-sup[0m([1;37mMR[0m): Gracefully departing from butterfly network.
[32mbuilder-sessionsrv.default[0m([1;37mSV[0m): Stopping...
[32mbuilder-sessionsrv.default[0m([1;37mO[0m):  INFO 2018-07-11T20:23:47Z: habitat_net::app: received shutdown signal, shutting down...
[32mbuilder-sessionsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:47Z: zmq: socket dropped
[32mbuilder-sessionsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:47Z: zmq: socket dropped
[32mbuilder-sessionsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:47Z: zmq: socket dropped
[32mbuilder-sessionsrv.default[0m([1;37mSV[0m): Shutdown OK: Graceful Termination
[32mbuilder-datastore.default[0m([1;37mSV[0m): Stopping...
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:47 GMT LOG:  received smart shutdown request
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:47 GMT LOG:  autovacuum launcher shutting down
[32mbuilder-worker.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: habitat_builder_worker::heartbeat: heartbeat pulsed: endpoint: "3555@ubuntu" os: Linux state: Ready
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: habitat_builder_jobsrv::server::worker_manager: Got heartbeat: endpoint: "3555@ubuntu" os: Linux state: Ready
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: postgres: executing query:
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: habitat_builder_db::pool: Switching to shard 0
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: postgres: preparing query with name ``: SET search_path TO shard_0
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: postgres: executing statement  with parameters: []
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: postgres: preparing query with name ``: SELECT * FROM get_cancel_pending_jobs_v1()
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: postgres: executing statement  with parameters: []
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: postgres: executing query:
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: habitat_builder_db::pool: Switching to shard 0
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: postgres: preparing query with name ``: SET search_path TO shard_0
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: postgres: executing statement  with parameters: []
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: postgres: preparing query with name ``: SELECT * FROM next_pending_job_v1($1)
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:51Z: postgres: executing statement  with parameters: ["3555@ubuntu"]
[32mbuilder-datastore.default[0m([1;37mSV[0m): Shutdown OK: Killed
[32mbuilder-minio.default[0m([1;37mSV[0m): Stopping...
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-minio.default[0m([1;37mO[0m): Exiting on signal terminated
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-datastore.default[0m([1;37mO[0m): 2018-07-11 20:23:55 GMT FATAL:  terminating connection due to unexpected postmaster exit
[32mbuilder-minio.default[0m([1;37mSV[0m): Shutdown OK: Graceful Termination
[32mbuilder-api-proxy.default[0m([1;37mSV[0m): Stopping...
[32mbuilder-api-proxy.default[0m([1;37mSV[0m): Shutdown OK: Graceful Termination
[32mbuilder-jobsrv.default[0m([1;37mSV[0m): Stopping...
[32mbuilder-jobsrv.default[0m([1;37mO[0m):  INFO 2018-07-11T20:23:55Z: habitat_net::app: received shutdown signal, shutting down...
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:55Z: zmq: socket dropped
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:55Z: zmq: socket dropped
[32mbuilder-jobsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:55Z: zmq: socket dropped
[32mbuilder-jobsrv.default[0m([1;37mSV[0m): Shutdown OK: Graceful Termination
[32mbuilder-originsrv.default[0m([1;37mSV[0m): Stopping...
[32mbuilder-originsrv.default[0m([1;37mO[0m):  INFO 2018-07-11T20:23:55Z: habitat_net::app: received shutdown signal, shutting down...
[32mbuilder-originsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:55Z: zmq: socket dropped
[32mbuilder-originsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:55Z: zmq: socket dropped
[32mbuilder-originsrv.default[0m([1;37mO[0m): DEBUG 2018-07-11T20:23:55Z: zmq: socket dropped
[32mbuilder-originsrv.default[0m([1;37mSV[0m): Shutdown OK: Graceful Termination
[32mbuilder-worker.default[0m([1;37mSV[0m): Stopping...
[32mbuilder-worker.default[0m([1;37mSV[0m): Shutdown OK: Graceful Termination
[32mbuilder-router.default[0m([1;37mSV[0m): Stopping...
[32mbuilder-router.default[0m([1;37mSV[0m): Shutdown OK: Graceful Termination
[32mbuilder-api.default[0m([1;37mSV[0m): Stopping...
[32mbuilder-api.default[0m([1;37mSV[0m): Shutdown OK: Graceful Termination
[32msccache.default[0m([1;37mSV[0m): Stopping...
[32msccache.default[0m([1;37mSV[0m): Shutdown OK: Graceful Termination
[36mhab-launch[0m([1;37mSV[0m): Hasta la vista, services.
ERROR 2018-07-11T20:23:55Z: hab_launch: Launcher exiting with code 0
```

**Comment by baumanj** [comment] 2018-07-11 20:58
I'd want to see what comes before 

```
�[36mhab-sup�[0m(�[1;37mMR�[0m): Gracefully departing from butterfly network.
```

Can you grep out the `hab-sup` and `hab-launch` logs? Whatever caused the supervisor to shut down happened before that, but all the previous lines aren't from the supervisor itself.

Also, turning up the log level of the sup and launcher specifically may help. Or, if you can find a consistent method to reproduce this, I'll dig in myself.

**Comment by baumanj** [comment] 2018-07-11 21:28
A simple thing to try to see if it's related to accidental killing is detaching the supervisor from the terminal's TTY. To see if that's the issue, you can modify the definition of `sup-run` in `/etc/profile` under your studio root. Or, if you want to change it for newly created studios as well, you'd have to change `/hab/pkgs/core/hab-studio/…/libexec/hab-studio-type-default.sh`.

Add the following line after `hab sup start` (previous line included for context):

```bash
  hab sup run "$@" > /hab/sup/default/sup.log 2>&1 &
  disown $!
```

You'll know it's working if `hab sup status` shows the supervisor is running but `jobs` doesn't show it.

**Comment by stevendanna** [comment] 2018-07-12 11:14
@baumanj Is spot on with the cause here I think.  The most common way I hit this is when I am impatient, go to interrupt some long running command, and but hit Ctrl^c too many times.  Because of how we start hab-sup, it shares a process group with the main shell (Ctrl^c sends SIGINT to the foreground process group, not just the foreground process).

We have 3-4 bugs about this I think :D.  It is really annoying.

**Comment by baumanj** [comment] 2018-07-12 13:12
Ooh, good point about the process group, @stevendanna.

Here's the issue that I filed for it: https://github.com/habitat-sh/habitat/issues/5271

I've been holding off because I wanted to finish https://github.com/habitat-sh/habitat/issues/5270 first for usability reasons, but maybe that's not necessary to do it first. In either case, I'll prioritize getting this in since it's causing problems for people. I'm on goalie duty and doing a release today so it probably won't be until Monday, but it should be pretty straightforward.

**Comment by baumanj** [comment] 2018-07-12 17:53
OK, I thought I had a fix for this, but now I'm not so sure. It appears that the supervisor is only subject to this accidental killing when it is automatically launched upon entering the studio:
```
➤ hab studio enter
…
--> Launching the Habitat Supervisor in the background…
…
[1][default:/src:0]# jobs
[1]+  Running                 hab sup run "$@" > /hab/sup/default/sup.log 2>&1 &  (wd: /)
[2][default:/src:0]# ^C
[2][default:/src:130]# jobs
[1]+  Done                    hab sup run "$@" > /hab/sup/default/sup.log 2>&1  (wd: /)
[3][default:/src:0]# hab sup status
✗✗✗
✗✗✗ Connection refused (os error 111)
✗✗✗
[4][default:/src:1]# logout

➤ env HAB_STUDIO_SUP=false hab studio enter
…
[1][default:/src:0]# jobs
[2][default:/src:0]# hab sup status
✗✗✗
✗✗✗ Connection refused (os error 111)
✗✗✗
[3][default:/src:1]# sup-run 
--> Launching the Habitat Supervisor in the background...
…
[4][default:/src:0]# ^C
[4][default:/src:130]# ^C
[4][default:/src:130]# jobs
[1]+  Running                 hab sup run "$@" > /hab/sup/default/sup.log 2>&1 &
[5][default:/src:0]# hab sup status
No services loaded.
```

I'm going to keep investigating.

I still think disowning is a good idea, but it's not the fix here.

**Comment by stevendanna** [comment] 2018-07-12 18:10
@baumanj It's been a while since I've read the bash manual, but I wonder if there is something particular wtih long-lived processes started in /etc/profile.  Another option is setsid or chpst to make sure we are getting a new process group

**Comment by baumanj** [comment] 2018-07-12 18:52
You're a wealth of useful info, @stevendanna! I shall investigate and report back.

**Comment by baumanj** [comment] 2018-07-17 16:03
It looks like the issue is not the session, but the process group. With the current code, when the supervisor is launched from `/etc/profile`, the process shares the same process group with `bash`, so signals get forwarded and a ^c on the CLI kills the supervisor (technically `hab-launch`).

If the supervisor is started from the command line, it still shares the session with `bash`, but has a different process group and so doesn't receive the signals. I'll have a PR up shortly to address all this.

**Closed** 2018-07-17 18:36 UTC
Labels: A-supervisor, C-bug, T-stability, V-sup
