### ISSUE TITLE
License Acceptance blocks --help, --version

### ISSUE THREAD

**Issue by clintoncwolfe** [habitat-sh/habitat#6545] opened 2019-05-12 05:32 UTC
When running license-bound versions of the `hab` CLI, the user is challenged to accept the license even when running with innocuous invocations such as `hab`, `hab --help`, and `hab --version`.

This prevents the user from discovering the correct command, `hab license accept`.

Ubuntu 18.04
hab 0.81.0/20190507225645

```
root@vagrant:~# hab
+---------------------------------------------+

            Chef License Acceptance


Before you can continue, 1 product license must be accepted.
View the license at https://www.chef.io/end-user-license-agreement

License that needs accepting:

  * Habitat

Do you accept the 1 product license? [yes/No/quit] N

If you do not accept this license you will not be able to use Chef products.

Do you accept the 1 product license? [yes/No/quit] quit
root@vagrant:~# hab --help
+---------------------------------------------+

            Chef License Acceptance


Before you can continue, 1 product license must be accepted.
View the license at https://www.chef.io/end-user-license-agreement

License that needs accepting:

  * Habitat

Do you accept the 1 product license? [yes/No/quit] quit
root@vagrant:~# hab --version
+---------------------------------------------+

            Chef License Acceptance


Before you can continue, 1 product license must be accepted.
View the license at https://www.chef.io/end-user-license-agreement

License that needs accepting:

  * Habitat

Do you accept the 1 product license? [yes/No/quit] quit
root@vagrant:~#
```

**Comment by baumanj** [comment] 2019-05-14 18:47
Maybe just add more explanatory text to the output here

**Comment by clintoncwolfe** [comment] 2019-05-17 05:27
FWIW, Chef InSpec does not block --version or --help; I don't know about other products.

**Comment by sirajrauff** [comment] 2019-06-24 15:03
Update on this ticket for 0.82.0, `--help` and `--version` are no longer blocked by the license, but seem to automatically accept the license:
```
$ ls -la
total 20
drwx------. 5 hab  hab   135 Jun 24 15:00 .
drwxr-xr-x. 4 root root   31 Jun 24 14:01 ..
-rw-------. 1 hab  hab    14 Jun 24 14:52 .bash_history
-rw-r--r--. 1 hab  hab    18 Oct 30  2018 .bash_logout
-rw-r--r--. 1 hab  hab   219 Jun 24 14:02 .bash_profile
-rw-r--r--. 1 hab  hab   231 Oct 30  2018 .bashrc
drwxr-xr-x. 3 hab  hab    25 Jun 24 14:50 .cache
drwxr-xr-x. 3 hab  hab    19 Jun 24 14:50 .local
drwxrw----. 3 hab  hab    19 Jun 24 14:58 .pki
-rw-------. 1 hab  hab  1024 Jun 24 14:50 .rnd

[hab@ip-172-31-43-94 ~]$ hab --version
hab 0.82.0/20190605214032

[hab@ip-172-31-43-94 ~]$ ls -la
total 20
drwx------. 6 hab  hab   147 Jun 24 15:01 .
drwxr-xr-x. 4 root root   31 Jun 24 14:01 ..
-rw-------. 1 hab  hab    14 Jun 24 14:52 .bash_history
-rw-r--r--. 1 hab  hab    18 Oct 30  2018 .bash_logout
-rw-r--r--. 1 hab  hab   219 Jun 24 14:02 .bash_profile
-rw-r--r--. 1 hab  hab   231 Oct 30  2018 .bashrc
drwxr-xr-x. 3 hab  hab    25 Jun 24 14:50 .cache
drwxrwxr-x. 3 hab  hab    31 Jun 24 15:01 .hab
drwxr-xr-x. 3 hab  hab    19 Jun 24 14:50 .local
drwxrw----. 3 hab  hab    19 Jun 24 14:58 .pki
-rw-------. 1 hab  hab  1024 Jun 24 14:50 .rnd

[hab@ip-172-31-43-94 ~]$ tree .hab
.hab
└── accepted-licenses
    └── habitat

1 directory, 1 file

[hab@ip-172-31-43-94 ~]$ cat .hab/accepted-licenses/habitat 
---
date_accepted: "2019-06-24T15:01:11.351342896Z"
accepting_product: hab
accepting_product_version: 0.82.0/20190605214032
user: hab
file_format: "1.0"
```
Is this intended behaviour?

**Comment by raskchanky** [comment] 2019-10-11 17:32
Unfortunately, due to some legacy architecture decisions, the `hab` CLI makes it difficult to support this type of behavior.  It's not impossible, but it's also not as trivial as it should be.  Since we're already presenting the user with the option of accepting the license, the discoverability of `hab license accept` doesn't seem super important.  Additionally, we have the command, as well as all of the ways to accept the license, documented on the Chef web site.  I'm going to close this for now, but if this is causing legitimate problems, feel free to reopen and we can discuss further.

**Closed by raskchanky** 2019-10-11 17:32 UTC
Labels: C-bug
