### ISSUE TITLE
`hab studio run` in windows only accepts single argument

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#6954] opened 2019-09-11 19:45 UTC
Observed on Windows 10,  Habitat 0.83.0

When executing `hab studio run` on Windows,  the Studio only receives the first argument passed: 

```
> hab studio run Write-Host "hello" 
...
   hab-studio: Running 'Write-Host' in Studio at c:\hab\studios....

>
``` 

When running an equivalent command on Linux,  the studio accepts multiple arguments:
```
$ hab studio run echo \$HOME
...
   hab-studio: Running 'echo $HOME' in Studio at /hab/studios/.... 
/root
```

**Comment by mwrock** [comment] 2019-09-16 20:47
duplicate of #6409

**Closed by mwrock** 2019-09-16 20:47 UTC
Labels: A-cli, C-bug, I-windows, V-bldr
