### ISSUE TITLE
Connecting existing plans should return a more specific error message

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#3923] opened 2017-10-27 02:40 UTC
Currently if you try to connect a plan that was already connected, you get an error "failed to save plan connection".  This came up in a slack conversation with @ariv3ra where he was trying to connect a plan and was repeatedly unable to do so. It ended up that his plan must have been saved but he was never redirected to the successful save view. 

I'm not sure why he wasn't redirected, but if we return an error message for 409s saying something like "your plan connection has already been saved," it may help users course correct more quickly and allow maintainers to better assist.

**Comment by cnunciato** [comment] 2017-10-27 17:46
This looks like a dupe of #3676, which is currently In Development. (cc @mgamini)

**Closed by cnunciato** 2017-10-27 17:46 UTC
Labels: A-builder, C-chore, E-easy

**Comment by jningtho** [comment] 2017-10-31 18:38
Hi Guys,
Post successful 'Save Connection' I don't see any options under 'Build Jobs', following step-by-step article : https://www.habitat.sh/demo/steps/8/. although I can see it in the connected plans. 
Trying to connect a plan with a different repo seems to throw error in the topic. 
Anyone is aware of this?

**Comment by tashimi** [comment] 2017-10-31 19:24
Hi @jningtho, we currently have a service outage that is limiting your ability to perform that step. I am so sorry for the inconvenience. We are publicly tracking the issue here: https://status.habitat.sh/ and will update when it is resolved.

**Comment by tashimi** [comment] 2017-11-06 21:30
Hi @jningtho,  

The problem you were experiencing is now resolved, please give it another shot and let me know if you have any problems. 

Thanks, Tasha

**Comment by ariv3ra** [comment] 2017-11-07 01:42
LGTM error is gone
Thx  @mwrock

**Comment by VickyWinner** [comment] 2018-06-06 17:01
is this issue fixed?  I am getting the same error "failed to save plan connection".

**Comment by mwrock** [comment] 2018-06-06 17:15
This issue was addressed in #3676. However, if you are receiving this error, please open a new issue. It would also be helpful if you can include the HTTP response you are receiving which may have more error/debugging info.
