### ISSUE TITLE
[bug] Binlink links to /bin in a studio, but only /hab/bin is available in the path

### ISSUE THREAD

**Issue by moretea** [habitat-sh/habitat#1680] opened 2017-01-26 14:50 UTC
How to reproduce:

1. `hab studio enter`
2. `hab pkg install core/curl`
3. `hab pkg binlink core/curl curl`

---

```
$ hab pkg install core/curl
[66][default:/src:130]# hab pkg binlink core/curl curl
» Symlinking curl from core/curl into /bin
★ Binary curl from core/curl/7.51.0/20161214014615 symlinked to /bin/curl
[67][default:/src:0]# curl
bash: curl: command not found
[69][default:/src:0]# /bin/
bash  curl  sh    
[69][default:/src:130]# echo $PATH
/hab/bin:/hab/pkgs/core/hab-plan-build/0.16.0/20170119211710/bin:/hab/pkgs/core/diffutils/3.3/20161208223733/bin:/hab/pkgs/core/less/481/20161213235230/bin:/hab/pkgs/core/make/4.2.1/20161214000256/bin:/hab/pkgs/core/mg/20160118/20161214223321/bin:/hab/pkgs/core/util-linux/2.27.1/20161214015006/bin:/hab/pkgs/core/vim/8.0.0004/20161215064031/bin:/hab/pkgs/core/ncurses/6.0/20161213233720/bin:/hab/pkgs/core/acl/2.2.52/20161208223311/bin:/hab/pkgs/core/attr/2.4.47/20161208223238/bin:/hab/pkgs/core/bash/4.3.42/20161213234235/bin:/hab/pkgs/core/binutils/2.25.1/20161208212141/bin:/hab/pkgs/core/bzip2/1.0.6/20161208225359/bin:/hab/pkgs/core/coreutils/8.25/20161208223423/bin:/hab/pkgs/core/file/5.24/20161208231044/bin:/hab/pkgs/core/findutils/4.4.2/20161208223828/bin:/hab/pkgs/core/gawk/4.1.3/20161208225252/bin:/hab/pkgs/core/glibc/2.22/20160612063629/bin:/hab/pkgs/core/grep/2.22/20161213233954/bin:/hab/pkgs/core/gzip/1.6/20161214000205/bin:/hab/pkgs/core/hab/0.16.0/20170119210110/bin:/hab/pkgs/core/libcap/2.24/20161208223353/bin:/hab/pkgs/core/libidn/1.32/20161214015159/bin:/hab/pkgs/core/openssl/1.0.2j/20161214012334/bin:/hab/pkgs/core/pcre/8.38/20161213233903/bin:/hab/pkgs/core/sed/4.2.2/20161208223647/bin:/hab/pkgs/core/tar/1.29/20161209183612/bin:/hab/pkgs/core/unzip/6.0/20161214012024/bin:/hab/pkgs/core/wget/1.18/20161214015248/bin:/hab/pkgs/core/xz/5.2.2/20161208230159/bin
```

**Comment by adamhjk** [comment] 2017-01-26 23:09
Feels like the right fix here is to include `/bin` in the studio path - what do you think, @fnichol?

**Comment by ShalokShalom** [comment] 2017-08-11 15:28
Confirmed, this counts at least from 0.23 until 0.29.1

![screenshot_20170811_172409](https://user-images.githubusercontent.com/6344099/29219985-f49e0082-7eb9-11e7-9e16-62b45dc6f0a0.png)

**Comment by reset** [comment] 2017-08-11 18:21
Duplicate of #975

**Closed by reset** 2017-08-11 18:21 UTC
Labels: C-bug, E-easy
