### ISSUE TITLE
Suggestion: Have search results link to sections of the page searched

### ISSUE THREAD

**Issue by onlyhavecans** [habitat-sh/habitat#4561] opened 2018-02-06 21:17 UTC
When I search for something in the reference guide the search feature does not take me to the nearest header or the first matching subsection of a page, it just drops me at the top. This means I have to search for things twice. Once through all the documentation and then locally on the page.

I would appreciate if we could get better-scoped searches.

**Comment by onlyhavecans** [comment] 2018-02-06 21:20
@apriofrost recommended I poke her on search changes in slack

**Comment by onlyhavecans** [comment] 2018-02-06 22:38
The search is so random; If I search for "environment variables" without quotes it takes me to https://www.habitat.sh/docs/search/#stq=environment+variables&stp=1

On this page for me looks like below
![screen shot 2018-02-06 at 14 36 41](https://user-images.githubusercontent.com/718435/35888040-329ead5a-0b4b-11e8-9e3b-3b1e6f3440f2.png)

That last result "Introducing Runtime Environment Variables" takes me to https://www.habitat.sh/blog/2017/08/community-summits/ which is about community summits. If I look all the way at the bottom of THIS page is a link to the actual article I want to read.

This is an extremely bad UI

**Comment by tashimi** [comment] 2018-02-07 23:35
@ryankeairns @brewn could you take a look at this?

**Comment by ryankeairns** [comment] 2018-02-08 14:29
@tashimi  This is a limitation of Swiftype that we've confirmed with their support team. In short, the main search results page does not return the anchor portion of indexed URLs, while the autocomplete dropdown results do.

I wonder if we could/should do without the main search results page and just use the small search with autocomplete only. It provides the desired anchor URLs and seems to be the common path of other popular open source docs pages:
- https://vuejs.org/v2/guide/
- https://getbootstrap.com/docs/4.0/getting-started/introduction/
- https://reactjs.org/docs/hello-world.html

I've noticed that some of the most popular open source projects (including vue and react, above) are using https://community.algolia.com/docsearch/ which is free for open source projects. It essentially does what I described above (no /search page, just an embedded search widget) and seems to work quite well. I went ahead and submitted our site, we'll see what it comes back with.

Lastly, we could also consider not using long pages with anchor links, instead favoring short pages with unique URLs, but that probably has other experience drawbacks that Nick might weigh in on.

**Comment by ryankeairns** [comment] 2018-02-12 21:24
**Update** - response from algolia:

Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:
- Copy the following CSS/JS snippets and add them to your page

```
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />
<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
 apiKey: '1fea8911b2652e889fb74698da75ef9c',
 indexName: 'habitat_sh',
 inputSelector: '### REPLACE ME ####',
 debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```
- Add a search input if you don't have any yet, and update the inputSelector value in the code snippet to a CSS selector that targets your input field.
- Optionally customize the look and feel by following the DocSearch documentation (https://community.algolia.com/docsearch/documentation/)
- You can also check your configuration in the github repo (https://github.com/algolia/docsearch-configs/blob/master/configs/habitat_sh.json).

**Comment by ryankeairns** [comment] 2018-02-12 21:26
I'll work on getting this into acceptance so that we can see how well it performs.

**Comment by ryankeairns** [comment] 2018-02-23 19:35
We implemented a new search tool that addresses this issue, so I'm closing it out.

For reference, the new search was added here https://github.com/habitat-sh/habitat/pull/4613

**Closed by ryankeairns** 2018-02-23 19:35 UTC
Labels: A-documentation, A-habitat.sh, L-html-css
