### ISSUE TITLE
style: Fix identation on hab svc status

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#5415] opened 2018-08-03 09:54 UTC
```
root@dokken:~# hab svc status
package                                              type        state  elapsed (s)  pid    group
chef-server/chef-server-ctl/12.17.50/20180504220656  standalone  up     3670         15725  chef-server-ctl.default
core/elasticsearch5/5.6.4/20180609194142  standalone  up  131  16408  elasticsearch5.default
core/postgresql/9.6.8/20180711204049  standalone  up  125  16490  postgresql.default
```

**Comment by raskchanky** [comment] 2018-08-03 17:04
This is a duplicate of https://github.com/habitat-sh/habitat/issues/5157

**Closed by raskchanky** 2018-08-03 17:04 UTC
