### ISSUE TITLE
problems with gossiped cfg information after upgrading from 0.19.0 to 0.25.1

### ISSUE THREAD

**Issue by bixu** [habitat-sh/habitat#2761] opened 2017-07-15 14:50 UTC
Apologies for the lack of clarity in this report - still trying to wrap my head around whats going on.

Post upgrade, we saw our HAProxy upstream servers IPs slowly expire from our config, leaving us (now) with HAProxy in a state like this (from the Sup logs):
```
172.31.13.129 Jul 15 14:20:52 100-edge-staging hab[721]: haproxy_harvester.staging(SR): Waiting for service binds...
172.31.12.91  Jul 15 14:20:52 101-edge-staging hab[12442]: haproxy_harvester.staging(SR): The specified service group 'api.staging' for binding 'backend' is not (yet?) present in the census data.
172.31.12.91  Jul 15 14:20:52 101-edge-staging hab[12442]: haproxy_harvester.staging(SR): Waiting for service binds...
172.31.12.91  Jul 15 14:20:52 101-edge-staging hab[12442]: haproxy_api.staging(SR): The specified service group 'api.staging' for binding 'backend' is not (yet?) present in the census data.
```
Our service start command looks like:
```
hab_service 'smartb/haproxy_api --group staging --bind "backend:api.staging --peer 100-api-staging.domain.tld
```

Here's some relevant Butterfly API output as requested by @reset:
'producer' (api host):
```
100-api-staging:~$ curl -s http://localhost:9631/butterfly
{"member":{"members":{"d0fbe4500fe34f768b51080d64c7f2f8":{"proto":{"id":"d0fbe4500fe34f768b51080d64c7f2f8","incarnation":0,"address":"172.31.12.91","swim_port":9638,"gossip_port":9638,"persistent":false}},"cbc1a2a52b274413bfd3492b11b39058":{"proto":{"id":"cbc1a2a52b274413bfd3492b11b39058","incarnation":3,"address":"172.31.7.198","swim_port":9638,"gossip_port":9638,"persistent":false}},"2efcacb22602496bb660dec74c3bba38":{"proto":{"id":"2efcacb22602496bb660dec74c3bba38","incarnation":0,"address":"172.31.14.186","swim_port":9638,"gossip_port":9638,"persistent":false}},"5b71341153ea4da5ae0d327b6fb51f0d":{"proto":{"id":"5b71341153ea4da5ae0d327b6fb51f0d","incarnation":0,"address":"172.31.13.129","swim_port":9638,"gossip_port":9638,"persistent":false}}},"health":{"2efcacb22602496bb660dec74c3bba38":"Alive","5b71341153ea4da5ae0d327b6fb51f0d":"Confirmed","cbc1a2a52b274413bfd3492b11b39058":"Alive","d0fbe4500fe34f768b51080d64c7f2f8":"Confirmed"},"update_counter":11},"service":{"list":{"nginx.default":{"cbc1a2a52b274413bfd3492b11b39058":{"type":2,"tag":[],"from_id":"cbc1a2a52b274413bfd3492b11b39058","service":{"member_id":"cbc1a2a52b274413bfd3492b11b39058","service_group":"nginx.default","package":"smartb/nginx/1.10.1/20170706103228","incarnation":1,"cfg":{},"sys":{"ip":"172.31.7.198","hostname":"proxy-staging-0","gossip_ip":"0.0.0.0","gossip_port":9638,"http_gateway_ip":"0.0.0.0","http_gateway_port":9631},"initialized":false}}},"api.staging":{"2efcacb22602496bb660dec74c3bba38":{"type":2,"tag":[],"from_id":"2efcacb22602496bb660dec74c3bba38","service":{"member_id":"2efcacb22602496bb660dec74c3bba38","service_group":"api.staging","package":"smartb/api/0.1.0/20170714170936","incarnation":4,"cfg":{"port":10000},"sys":{"ip":"172.31.14.186","hostname":"100-api-staging","gossip_ip":"0.0.0.0","gossip_port":9638,"http_gateway_ip":"0.0.0.0","http_gateway_port":9631},"initialized":false}}},"haproxy_api.staging":{"cbc1a2a52b274413bfd3492b11b39058":{"type":2,"tag":[],"from_id":"cbc1a2a52b274413bfd3492b11b39058","service":{"member_id":"cbc1a2a52b274413bfd3492b11b39058","service_group":"haproxy_api.staging","package":"smartb/haproxy_api/1.6.11/20170714185533","incarnation":5,"cfg":{"port":8001,"status-port":9001},"sys":{"ip":"172.31.7.198","hostname":"proxy-staging-0","gossip_ip":"0.0.0.0","gossip_port":9638,"http_gateway_ip":"0.0.0.0","http_gateway_port":9631},"initialized":false}}}},"update_counter":10},"service_config":{"list":{},"update_counter":0},"service_file":{"list":{},"update_counter":0},"election":{"list":{},"update_counter":0},"election_update":{"list":{},"update_counter":0}}
```

'consumer' (haproxy host):
```
100-edge-staging:~$ curl -s localhost:9631/butterfly
{"member":{"members":{},"health":{},"update_counter":0},"service":{"list":{"haproxy_harvester.staging":{"0dd446fbe25e420288dab6f3fa52d1f6":{"type":2,"tag":[],"from_id":"0dd446fbe25e420288dab6f3fa52d1f6","service":{"member_id":"0dd446fbe25e420288dab6f3fa52d1f6","service_group":"haproxy_harvester.staging","package":"smartb/haproxy_harvester/1.6.11/20170316202801","incarnation":1,"cfg":{"port":8000,"status-port":9000},"sys":{"ip":"172.31.13.129","hostname":"100-edge-staging","gossip_ip":"0.0.0.0","gossip_port":9638,"http_gateway_ip":"0.0.0.0","http_gateway_port":9631},"initialized":false}}},"haproxy_api.staging":{"0dd446fbe25e420288dab6f3fa52d1f6":{"type":2,"tag":[],"from_id":"0dd446fbe25e420288dab6f3fa52d1f6","service":{"member_id":"0dd446fbe25e420288dab6f3fa52d1f6","service_group":"haproxy_api.staging","package":"smartb/haproxy_api/1.6.11/20170316202648","incarnation":1,"cfg":{"port":8001,"status-port":9001},"sys":{"ip":"172.31.13.129","hostname":"100-edge-staging","gossip_ip":"0.0.0.0","gossip_port":9638,"http_gateway_ip":"0.0.0.0","http_gateway_port":9631},"initialized":false}}}},"update_counter":2},"service_config":{"list":{},"update_counter":0},"service_file":{"list":{},"update_counter":0},"election":{"list":{},"update_counter":0},"election_update":{"list":{},"update_counter":0}}
```

**Comment by adamhjk** [comment] 2017-07-15 14:55
Formatted output:

# Producer

```javascript
{
  "member": {
    "members": {
      "d0fbe4500fe34f768b51080d64c7f2f8": {
        "proto": {
          "id": "d0fbe4500fe34f768b51080d64c7f2f8",
          "incarnation": 0,
          "address": "172.31.12.91",
          "swim_port": 9638,
          "gossip_port": 9638,
          "persistent": false
        }
      },
      "cbc1a2a52b274413bfd3492b11b39058": {
        "proto": {
          "id": "cbc1a2a52b274413bfd3492b11b39058",
          "incarnation": 3,
          "address": "172.31.7.198",
          "swim_port": 9638,
          "gossip_port": 9638,
          "persistent": false
        }
      },
      "2efcacb22602496bb660dec74c3bba38": {
        "proto": {
          "id": "2efcacb22602496bb660dec74c3bba38",
          "incarnation": 0,
          "address": "172.31.14.186",
          "swim_port": 9638,
          "gossip_port": 9638,
          "persistent": false
        }
      },
      "5b71341153ea4da5ae0d327b6fb51f0d": {
        "proto": {
          "id": "5b71341153ea4da5ae0d327b6fb51f0d",
          "incarnation": 0,
          "address": "172.31.13.129",
          "swim_port": 9638,
          "gossip_port": 9638,
          "persistent": false
        }
      }
    },
    "health": {
      "2efcacb22602496bb660dec74c3bba38": "Alive",
      "5b71341153ea4da5ae0d327b6fb51f0d": "Confirmed",
      "cbc1a2a52b274413bfd3492b11b39058": "Alive",
      "d0fbe4500fe34f768b51080d64c7f2f8": "Confirmed"
    },
    "update_counter": 11
  },
  "service": {
    "list": {
      "nginx.default": {
        "cbc1a2a52b274413bfd3492b11b39058": {
          "type": 2,
          "tag": [],
          "from_id": "cbc1a2a52b274413bfd3492b11b39058",
          "service": {
            "member_id": "cbc1a2a52b274413bfd3492b11b39058",
            "service_group": "nginx.default",
            "package": "smartb/nginx/1.10.1/20170706103228",
            "incarnation": 1,
            "cfg": {},
            "sys": {
              "ip": "172.31.7.198",
              "hostname": "proxy-staging-0",
              "gossip_ip": "0.0.0.0",
              "gossip_port": 9638,
              "http_gateway_ip": "0.0.0.0",
              "http_gateway_port": 9631
            },
            "initialized": false
          }
        }
      },
      "api.staging": {
        "2efcacb22602496bb660dec74c3bba38": {
          "type": 2,
          "tag": [],
          "from_id": "2efcacb22602496bb660dec74c3bba38",
          "service": {
            "member_id": "2efcacb22602496bb660dec74c3bba38",
            "service_group": "api.staging",
            "package": "smartb/api/0.1.0/20170714170936",
            "incarnation": 4,
            "cfg": {
              "port": 10000
            },
            "sys": {
              "ip": "172.31.14.186",
              "hostname": "100-api-staging",
              "gossip_ip": "0.0.0.0",
              "gossip_port": 9638,
              "http_gateway_ip": "0.0.0.0",
              "http_gateway_port": 9631
            },
            "initialized": false
          }
        }
      },
      "haproxy_api.staging": {
        "cbc1a2a52b274413bfd3492b11b39058": {
          "type": 2,
          "tag": [],
          "from_id": "cbc1a2a52b274413bfd3492b11b39058",
          "service": {
            "member_id": "cbc1a2a52b274413bfd3492b11b39058",
            "service_group": "haproxy_api.staging",
            "package": "smartb/haproxy_api/1.6.11/20170714185533",
            "incarnation": 5,
            "cfg": {
              "port": 8001,
              "status-port": 9001
            },
            "sys": {
              "ip": "172.31.7.198",
              "hostname": "proxy-staging-0",
              "gossip_ip": "0.0.0.0",
              "gossip_port": 9638,
              "http_gateway_ip": "0.0.0.0",
              "http_gateway_port": 9631
            },
            "initialized": false
          }
        }
      }
    },
    "update_counter": 10
  },
  "service_config": {
    "list": {},
    "update_counter": 0
  },
  "service_file": {
    "list": {},
    "update_counter": 0
  },
  "election": {
    "list": {},
    "update_counter": 0
  },
  "election_update": {
    "list": {},
    "update_counter": 0
  }
}
```

# Consumer
```javascript
{
  "member": {
    "members": {},
    "health": {},
    "update_counter": 0
  },
  "service": {
    "list": {
      "haproxy_harvester.staging": {
        "0dd446fbe25e420288dab6f3fa52d1f6": {
          "type": 2,
          "tag": [],
          "from_id": "0dd446fbe25e420288dab6f3fa52d1f6",
          "service": {
            "member_id": "0dd446fbe25e420288dab6f3fa52d1f6",
            "service_group": "haproxy_harvester.staging",
            "package": "smartb/haproxy_harvester/1.6.11/20170316202801",
            "incarnation": 1,
            "cfg": {
              "port": 8000,
              "status-port": 9000
            },
            "sys": {
              "ip": "172.31.13.129",
              "hostname": "100-edge-staging",
              "gossip_ip": "0.0.0.0",
              "gossip_port": 9638,
              "http_gateway_ip": "0.0.0.0",
              "http_gateway_port": 9631
            },
            "initialized": false
          }
        }
      },
      "haproxy_api.staging": {
        "0dd446fbe25e420288dab6f3fa52d1f6": {
          "type": 2,
          "tag": [],
          "from_id": "0dd446fbe25e420288dab6f3fa52d1f6",
          "service": {
            "member_id": "0dd446fbe25e420288dab6f3fa52d1f6",
            "service_group": "haproxy_api.staging",
            "package": "smartb/haproxy_api/1.6.11/20170316202648",
            "incarnation": 1,
            "cfg": {
              "port": 8001,
              "status-port": 9001
            },
            "sys": {
              "ip": "172.31.13.129",
              "hostname": "100-edge-staging",
              "gossip_ip": "0.0.0.0",
              "gossip_port": 9638,
              "http_gateway_ip": "0.0.0.0",
              "http_gateway_port": 9631
            },
            "initialized": false
          }
        }
      }
    },
    "update_counter": 2
  },
  "service_config": {
    "list": {},
    "update_counter": 0
  },
  "service_file": {
    "list": {},
    "update_counter": 0
  },
  "election": {
    "list": {},
    "update_counter": 0
  },
  "election_update": {
    "list": {},
    "update_counter": 0
  }
}
```

**Comment by adamhjk** [comment] 2017-07-15 15:06
First glance, this feels like a connectivity problem. If the system was working at all, you would see membership records in the consumer output - this means that it hasn't received any UDP traffic at all.

**Comment by smartb-pair** [comment] 2017-07-19 17:06
Adding commentary to this, it seems to us (@bixu and colleagues that work together as @smartb-pair) that part of the problem is that our API service group member is not marked 'alive'(from our `census.dat` on the producer (api) side of the connection):
```
 "alive": false,
          "suspect": false,
          "confirmed": false,
```

**Comment by smartb-pair** [comment] 2017-07-19 17:24
To add to the confusion, just saw a behavior where the following commands brought the API member back to an `alive` state:
```
systemctl stop habitat-supervisor.service
systemctl start habitat-supervisor.service
```
SystemD unit file:
```
root@100-api-staging:~# cat /etc/systemd/system/habitat-supervisor.service
[Unit]
Description=The Habitat Supervisor

[Service]
Restart=always
ExecStart=/bin/hab sup run

[Install]
WantedBy=default.target
```
`census.dat` on the API service side:
```
root@100-edge-staging:~# cat /hab/sup/default/data/census.dat | jq .
{
  "changed": true,
  "census_groups": {
...
    "api.staging": {
      "service_group": "api.staging",
      "election_status": "None",
      "update_election_status": "None",
      "leader_id": null,
      "service_config": null,
      "local_member_id": "ef0f9d8c30c249a7804bacb94dc2670d",
      "population": {
        "add04e8aa699417587f1c53845f1f5e3": {
          "member_id": "add04e8aa699417587f1c53845f1f5e3",
          "pkg": {
            "origin": "smartb",
            "name": "api",
            "version": "0.1.0",
            "release": "20170719163151"
          },
          "service": "api",
          "group": "staging",
          "org": null,
          "initialized": false,
          "persistent": true,
          "leader": false,
          "follower": false,
          "update_leader": false,
          "update_follower": false,
          "election_is_running": false,
          "election_is_no_quorum": false,
          "election_is_finished": false,
          "update_election_is_running": false,
          "update_election_is_no_quorum": false,
          "update_election_is_finished": false,
          "alive": true,
          "suspect": false,
          "confirmed": false,
...
```

**Comment by smartb-pair** [comment] 2017-07-19 18:13
Thinking aloud:
- How does the Supervisor determine a service started by a simple `run` hook is 'alive'?
- Would have a `health_check` hook help here?
- Does our Ansible code for starting the service look sane?
```
- name: "create api config directory"
  file:
    path: /hab/svc/api/
    state: directory
    mode: 0750
    owner: hab
    group: hab

- name: "create api.toml config"
  template:
    src: api.toml.j2
    dest: /hab/svc/api/user.toml
    owner: hab
    mode: 0600

- name: "install api"
  become: true
  become_user: root
  shell: "hab install /root/<artifact>"

- name: "start habitat-supervised api service"
  shell: "hab svc start smartb/api --group <group> --peer 100-api-<group>.domain.tld"

- name: "start habitat-supervised api service"
  shell: "hab svc start smartb/api --group <group> --peer 100-api-<group>.domain.tld"

- name: "start habitat-supervised 'harvester' api service"
  shell: "hab svc start smartb/api --group <group> --peer 100-api-<group>.domain.tld"

- name: "restart api"
  shell: "hab svc stop smartb/api && hab svc start smartb/api"
```

**Comment by bixu** [comment] 2017-07-20 09:04
Thinking about this some more with @mspringfeldt this morning, we are wondering if this might be due to the non-standard way uWSGI (which is the app server for our API) handles `SIGTERM`: http://uwsgi-docs.readthedocs.io/en/latest/Upstart.html#what-is-die-on-term

Right after implementing a workaround, I went on to fix a bug with slow restarts of our API (restarts taking 1min30sec, which is the timeout for SystemD services). We now set
```
die-on-term = true
```
in our uWSGI config so that uWSGI respects `SIGTERM` and shuts down instead of reloading. Simultaneously, we seem to be properly consuming membership data from our API service group now.

Could it be that a child process not properly exiting on `SIGTERM` might cause the bug-like behavior we've been seeing?

**Comment by bixu** [comment] 2017-07-20 09:12
Further confirming my suspicions, here's the the contents of `census.dat` just before a restart of the now-properly-respecting-SIGTERM API service:
```
$ cat /hab/sup/default/data/census.dat | jq "." | grep -A32 "api\.staging" | tail -n3
          "alive": false,
          "suspect": false,
          "confirmed": false,
```
...and immediately after the restart:
```
$ cat /hab/sup/default/data/census.dat | jq "." | grep -A32 "api\.staging" | tail -n3
          "alive": true,
          "suspect": false,
          "confirmed": false,
```

**Comment by eeyun** [comment] 2017-07-25 19:44
@adamhjk and @bixu, @smartb-pair can you all verify whether this was resolved last week or continues to be an issue?

Have we found a way to replicate this behavior?

**Comment by bixu** [comment] 2017-07-25 21:34
We ended up bypassing gossiping the configs and are now just dropping off a template with Chef. We couldn't get a consistently reproducible failure in Test Kitchen, unfortunately.

I still suspect this is related to 'unclean' service restarts (which would tie into my RFE about synchronous service start/stop).

**Comment by reset** [comment] 2017-07-27 18:57
Fixed by https://github.com/habitat-sh/habitat/pull/2830 and going out in today's release

**Closed by reset** 2017-07-27 18:57 UTC
Labels: A-supervisor

**Comment by bixu** [comment] 2017-07-27 19:53
https://s-media-cache-ak0.pinimg.com/originals/9b/f5/b8/9bf5b82fb91f343fdc8ce885119552d6.gif

**Comment by bixu** [comment] 2017-07-27 19:55
![img_0890](https://user-images.githubusercontent.com/339799/28689554-5212b08c-7316-11e7-933f-63bde2f1dff4.GIF)
