### ISSUE TITLE
Possible bug: supervisor rendering config before gossip propagates

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#1557] opened 2016-12-12 19:04 UTC
Supervisor reads census list and renders config *before* gossip has time to populate census list on boot

**Comment by smith** [comment] 2017-01-29 20:39
Is this a duplicate of #1489 or something else?

**Comment by reset** [comment] 2017-01-29 21:00
It's basically a duplicate of #1489. I think this needs to be closed, though, because in general we can't wait for additional gossip data to come through before we act on starting our supervisor. If we did that, nobody would ever initialize and nobody would gossip about themselves. Basicaly, we shouldn't perform any timing coordinations unless a topology is being used. The one exception to this I'll post in #1489 - we need to address that and we have a solution

**Closed by reset** 2017-01-29 21:00 UTC
