### ISSUE TITLE
Add support for running multiple services to docker export

### ISSUE THREAD

**Issue by gmiranda23** [habitat-sh/habitat#2217] opened 2017-05-03 19:26 UTC
This feature request may be related to #2086 

Fix/tweak the `hab pkg export docker` code to assume that each ARGV is a service-runnable package identifier and call `hab service load <ident>` for each in the image creation.

According to Fletcher, the current code already technically takes multiple arguments and currently assumes  that the *first* one is your service package. It should be possible to change the assumption in the code without really breaking anyone.

The intended use case for this feature is to support InSpec + Habitat integration in Docker containers as per [this demo](https://www.youtube.com/watch?v=07c-7yJraK0).

**Comment by reset** [comment] 2017-08-03 22:48
Duplicate of #2086

**Closed by reset** 2017-08-03 22:48 UTC
Labels: A-cli, C-feature
