### ISSUE TITLE
Nodes can become duplicated in the Gossip Ring

### ISSUE THREAD

**Issue by benr** [habitat-sh/habitat#899] opened 2016-06-17 01:26 UTC
After creating a ring of supervisors, if the first node (the one that didn't peer to another) goes down and starts back up, it will become duplicated in the ring.  

In the example below the ring was established, then the first node (.191) was shutdown and started again by peering with another member of the ring.  I then stopped it and restarted it again.  This resulted in 3 member entries, each with a different ID.

```
$ curl -s 172.31.11.191:9631/gossip | jq -c '.member_list.members[] | [(.ip,.id,.health)]'
["172.31.11.191","fde15cb1-81d5-470e-8ec2-50f422051b75","Alive"]
["172.31.7.147","9cc27829-0749-4be5-a7d8-11b4469e9cf0","Alive"]
["172.31.11.191","5d32161f-8b4a-4e26-97e3-fa22e424f69b","Confirmed"]
["172.31.2.28","6a17b272-9d3e-4770-a9c8-74ce2c9e932c","Alive"]
["172.31.18.192","967c6fc7-ed42-4a50-ac63-0f8184c9f3f8","Alive"]
["172.31.11.191","c94ff543-e022-4134-b528-b87ce4c972bb","Confirmed"]
```

Furthermore, once a node has become duplicated like this, it doesn't accept being peered against again.

```
# hab start chefops/elasticsearch --org chefops --peer=172.31.11.191
hab-sup(MN): Starting chefops/elasticsearch
hab-sup(GS): Supervisor 172.31.7.147: a2c333fc-2f11-4c8a-87d3-ba0a14f82867
hab-sup(GS): Census elasticsearch.default: 66866a39-5b07-4416-865a-30f5b72f03bd
hab-sup(GS): Starting inbound gossip listener
hab-sup(GS): Joining gossip peer at 172.31.11.191:9634
hab-sup(GS): Failed to create a gossip client for 172.31.11.191:9634
hab-sup(GS): Could not connect to any initial peers; attempt 1 of 10.
hab-sup(GS): Joining gossip peer at 172.31.11.191:9634
hab-sup(GS): Failed to create a gossip client for 172.31.11.191:9634
hab-sup(GS): Could not connect to any initial peers; attempt 2 of 10.
hab-sup(GS): Joining gossip peer at 172.31.11.191:9634
...
```

**Comment by adamhjk** [comment] 2016-06-23 20:06
The first part, that there are multiple peers, and they are marked 'confirmed' is as designed. The supervisor instances themselves are what become peers, and each supervisor creates a new uuid at startup. In this case, there really were 3 different instances. There is a separate, and interesting, feature request about how you tombstone dead entries over time.

The second part of this, though, where it no longer accepts peers - that's bad news, and we should investigate and fix.

**Comment by abrooke** [comment] 2016-07-16 15:33
I was investigating this bug by looking to create a test to reproduce the bug and came across the following tests being 'ignored' which appear to be the type of tests that fit with this category of failure. The tests may have moved, however I can't find the new ones. Are these tests supposed to be 'ignored'? If so, where are the similar new tests so I can try to create a reproducible test for this bug? The tests were ignored in commit [Re-organize Rust component building & testing in Makefile.](https://github.com/habitat-sh/habitat/commit/6fcc39c611c97e4be079fa336d4896ba75d75d4a)

`/src/components/sup# cargo test --features functional`

```
test bldr_build::builds_a_service ... ignored
test sup_tests::gossip::incarnation_updates_on_suspicion ... ignored
test sup_tests::gossip::isolated_members_find_a_way_to_rejoin ... ignored
test sup_tests::gossip::members_are_gossiped ... ignored
test sup_tests::gossip::ressurection_of_permanent_members ... ignored
test sup_tests::gossip::routes_around_failure ... ignored
test sup_tests::gossip::two_supervisors_detect_failure ... ignored
test sup_tests::gossip::two_supervisors_link ... ignored
test sup_tests::start::leader_with_discovery ... ignored
test sup_tests::start::standalone_no_options ... ignored
test sup_tests::start::standalone_no_options_without_config ... ignored
test sup_tests::start::standalone_with_discovery_config ... ignored
test sup_tests::start::standalone_with_discovery_config_updates ... ignored
test sup_tests::start::standalone_with_environment_config ... ignored
test sup_tests::topology::leader::elects_a_leader ... ignored
test sup_tests::topology::leader::elects_on_failure ... ignored
test sup_tests::topology::leader::leader_without_quorum_stops_service_remainder_elects_new_leader ... ignored
test sup_tests::topology::leader::minimum_quorum ... ignored
```

**Comment by abrooke** [comment] 2016-07-16 15:36
@fnichol Brining your attention to above comment since the commit was yours Fletcher.

**Comment by metadave** [comment] 2016-07-18 17:08
The tests were ignored during a large code reorganization before the release, but _should_ eventually be re-enabled after a decent refactor (to make them work with a newer package format etc). I don't know if this task has been prioritized.

ping @juliandunn

**Comment by eeyun** [comment] 2017-03-07 20:57
Thank you for opening this issue. We believe that this particular issue has aged out as we've rewritten the gossip layer since this was opened. For now we are going to close this issue. If this remains a problem with more recent iterations of the gossip layer we would prefer  to have a new issue opened rather than reopening this one.

Thank you again!

**Closed by eeyun** 2017-03-07 20:57 UTC
Labels: Backlog, Bug, Supervisor
