### ISSUE TITLE
Blocking `init` hook prevents further supervisor interaction

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#5150] opened 2018-06-04 16:50 UTC
Consider an `init` hook with the following content:

```
#!/bin/sh

head -1 /tmp/mypipe
```

where `mypipe` is a named pipe (this is just to simulate some blocking operation):

```
mkfifo /tmp/mypipe
hab svc load ssd/my-test-service
```

The supervisor is now blocked and will not respond to further, load, unload, or status requests. Note, that in some cases the initial load itself fails to return, but in other cases it does return and it is just subsequent commands that block.

I've reproduced this on 0.56.0, but similar behavior exists on 0.55.0.

**Comment by mgamini** [comment] 2018-06-05 17:21
@reset will this be resolved with your upcoming changes?

**Comment by reset** [comment] 2018-06-05 19:38
Yes, this is a duplicate of https://github.com/habitat-sh/habitat/issues/1973

**Comment by christophermaier** [comment] 2018-06-21 21:52
Closing this issue in favor of #1973

**Closed** 2018-06-21 21:53 UTC
